import { Product, Category, Review } from "@/types";
import { Settings, Circle, Droplets, Zap, GitMerge, Wheat } from "lucide-react";

export const categories: Category[] = [
  {
    id: 1,
    name: "Engine Parts",
    slug: "engine-parts",
    description: "High-performance engine components for all major tractor brands including John Deere, Massey Ferguson, New Holland, and Kubota. From pistons to fuel injectors.",
    productCount: 125,
    image: "https://images.unsplash.com/photo-1580983559367-0dc2f8934365?w=600&q=80",
    icon: "⚙️",
  },
  {
    id: 2,
    name: "Tires & Wheels",
    slug: "tires-wheels",
    description: "Agricultural tires and wheels for optimal traction in Nigerian terrain. Front and rear tractor tires, rims, and accessories.",
    productCount: 80,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    icon: "🔧",
  },
  {
    id: 3,
    name: "Hydraulics",
    slug: "hydraulics",
    description: "Complete hydraulic systems, pumps, cylinders, hoses, and control valves for agricultural machinery and tractors.",
    productCount: 65,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    icon: "💧",
  },
  {
    id: 4,
    name: "Electrical",
    slug: "electrical",
    description: "Alternators, starters, batteries, wiring harnesses, and electronic control modules for modern and classic tractors.",
    productCount: 90,
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
    icon: "⚡",
  },
  {
    id: 5,
    name: "Hydraulic Systems",
    slug: "hydraulic-systems",
    description: "Complete hydraulic lift assemblies, 3-point hitch components, and power steering systems.",
    productCount: 45,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    icon: "🔩",
  },
  {
    id: 6,
    name: "Implements",
    slug: "implements",
    description: "Ploughs, disc harrows, cultivators, seeders, and other agricultural implements for Nigerian farming operations.",
    productCount: 55,
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    icon: "🌾",
  },
];

// export const categories: Category[] = [
//   {
//     id: 1,
//     name: "Engine Parts",
//     slug: "engine-parts",
//     description: "High-performance engine components for all major tractor brands including John Deere, Massey Ferguson, New Holland, and Kubota. From pistons to fuel injectors.",
//     productCount: 125,
//     image: "https://images.unsplash.com/photo-1580983559367-0dc2f8934365?w=600&q=80",
//     icon: Settings,
//   },
//   {
//     id: 2,
//     name: "Tires & Wheels",
//     slug: "tires-wheels",
//     description: "Agricultural tires and wheels for optimal traction in Nigerian terrain. Front and rear tractor tires, rims, and accessories.",
//     productCount: 80,
//     image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
//     icon: Circle,
//   },
//   {
//     id: 3,
//     name: "Hydraulics",
//     slug: "hydraulics",
//     description: "Complete hydraulic systems, pumps, cylinders, hoses, and control valves for agricultural machinery and tractors.",
//     productCount: 65,
//     image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
//     icon: Droplets,
//   },
//   {
//     id: 4,
//     name: "Electrical",
//     slug: "electrical",
//     description: "Alternators, starters, batteries, wiring harnesses, and electronic control modules for modern and classic tractors.",
//     productCount: 90,
//     image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
//     icon: Zap,
//   },
//   {
//     id: 5,
//     name: "Hydraulic Systems",
//     slug: "hydraulic-systems",
//     description: "Complete hydraulic lift assemblies, 3-point hitch components, and power steering systems.",
//     productCount: 45,
//     image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
//     icon: GitMerge,
//   },
//   {
//     id: 6,
//     name: "Implements",
//     slug: "implements",
//     description: "Ploughs, disc harrows, cultivators, seeders, and other agricultural implements for Nigerian farming operations.",
//     productCount: 55,
//     image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
//     icon: Wheat,
//   },
// ];

export const products: Product[] = [
  {
    id: 1,
    name: "Diesel Engine Oil Filter",
    slug: "diesel-engine-oil-filter",
    description: "Premium diesel engine oil filter compatible with John Deere and Massey Ferguson tractors. Ensures clean oil circulation and extends engine life. Meets OEM specifications for optimal performance in Nigerian agricultural conditions.",
    shortDescription: "Compatible with John Deere, Massey Ferguson",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "Kubota / OEM Compatible",
    compatibility: "John Deere 5055E, 5075E; Massey Ferguson 265, 275, 290",
    rating: 4.5,
    reviewCount: 24,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80",
    featured: true,
    inStock: true,
    specs: {
      "Filter Type": "Full-flow Oil Filter",
      "Thread Size": "3/4-16 UNF",
      "Height": "140mm",
      "Outside Diameter": "96mm",
      "Bypass Valve": "Yes",
    },
    tags: ["oil filter", "engine filter", "john deere parts", "massey ferguson parts", "diesel engine"],
  },
  {
    id: 2,
    name: "Rear Tractor Tire 13.6-28",
    slug: "rear-tractor-tire-13-6-28",
    description: "Heavy-duty rear tractor tire size 13.6-28 suitable for 50-75HP tractors. Deep lug pattern provides excellent traction on Nigerian farm terrain including wet and muddy conditions.",
    shortDescription: "Fits most 50-75HP tractors",
    category: "Tires & Wheels",
    categorySlug: "tires-wheels",
    brand: "BKT / Equivalent",
    compatibility: "Most 50-75HP utility tractors",
    rating: 5,
    reviewCount: 37,
    badge: "New Arrival",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    featured: true,
    inStock: true,
    specs: {
      "Size": "13.6-28",
      "Ply Rating": "8PR",
      "Pattern": "R-1 Agricultural",
      "Load Index": "116A8",
      "Speed Symbol": "A8",
    },
    tags: ["tractor tire", "rear tire", "agricultural tire", "farm tire", "13.6-28"],
  },
  {
    id: 3,
    name: "Hydraulic Pump Assembly",
    slug: "hydraulic-pump-assembly",
    description: "Complete hydraulic pump assembly for John Deere 5055D and 5060E tractors. Delivers consistent hydraulic pressure for lift systems, power steering, and implement control. Direct replacement with no modification required.",
    shortDescription: "John Deere 5055D, 5060E",
    category: "Hydraulics",
    categorySlug: "hydraulics",
    brand: "OEM Compatible",
    compatibility: "John Deere 5055D, 5060E, 5065E",
    rating: 4.5,
    reviewCount: 18,
    badge: "Top Rated",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    featured: true,
    inStock: true,
    specs: {
      "Flow Rate": "32 L/min",
      "Operating Pressure": "200 bar",
      "Drive Type": "Gear Drive",
      "Port Size": "3/4\" BSP",
    },
    tags: ["hydraulic pump", "john deere hydraulics", "tractor hydraulics", "pump assembly"],
  },
  {
    id: 4,
    name: "Plough Implement",
    slug: "plough-implement",
    description: "Heavy-duty disc plough with universal 3-point hitch attachment. Ideal for primary tillage in Nigerian soil conditions. Adjustable working depth and disc angle for various crop types.",
    shortDescription: "Universal 3-point hitch",
    category: "Implements",
    categorySlug: "implements",
    brand: "Fieldking",
    compatibility: "Universal 3-point hitch, Cat I & II",
    rating: 4,
    reviewCount: 22,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    featured: true,
    inStock: true,
    specs: {
      "Type": "Disc Plough",
      "Number of Discs": "3",
      "Disc Diameter": "610mm",
      "Working Depth": "200-350mm",
      "Hitch Type": "Cat I & II 3-point",
    },
    tags: ["plough", "disc plough", "farm implement", "tillage", "agricultural implement"],
  },
  {
    id: 5,
    name: "Front Tractor Tire 6.00-16",
    slug: "front-tractor-tire-6-00-16",
    description: "Quality front tractor tire size 6.00-16 for utility tractors. Ribbed pattern for smooth steering and road transport. Compatible with most utility tractors used across Nigeria.",
    shortDescription: "Fits most utility tractors",
    category: "Tires & Wheels",
    categorySlug: "tires-wheels",
    brand: "BKT / Equivalent",
    compatibility: "Most utility tractors with F2 front axle",
    rating: 4.5,
    reviewCount: 15,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    featured: true,
    inStock: true,
    specs: {
      "Size": "6.00-16",
      "Ply Rating": "6PR",
      "Pattern": "F-2 Ribbed",
    },
    tags: ["front tire", "tractor tire", "utility tractor tire", "6.00-16"],
  },
  {
    id: 6,
    name: "Engine Gasket Set",
    slug: "engine-gasket-set",
    description: "Complete engine gasket set for Massey Ferguson 265 and 275 tractors. Includes head gasket, valve cover gasket, intake/exhaust manifold gaskets, and all necessary seals. Premium materials for long-lasting performance.",
    shortDescription: "Massey Ferguson 265, 275",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265, 275, 290",
    rating: 5,
    reviewCount: 29,
    badge: "New Arrival",
    image: "https://images.unsplash.com/photo-1580983559367-0dc2f8934365?w=600&q=80",
    featured: true,
    inStock: true,
    specs: {
      "Contents": "Full Engine Gasket Set",
      "Gaskets Included": "28 pieces",
      "Material": "Multi-layer Steel / Graphite",
    },
    tags: ["gasket set", "engine gasket", "massey ferguson parts", "head gasket", "engine rebuild"],
  },
  {
    id: 7,
    name: "Alternator 14V 65A",
    slug: "alternator-14v-65a",
    description: "Heavy-duty alternator for John Deere and New Holland tractors. Provides reliable charging for all electrical systems. Direct bolt-on replacement with no wiring modifications needed.",
    shortDescription: "John Deere, New Holland compatible",
    category: "Electrical",
    categorySlug: "electrical",
    brand: "Bosch Compatible",
    compatibility: "John Deere 5000 series, New Holland TD series",
    rating: 4.5,
    reviewCount: 19,
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
    featured: false,
    inStock: true,
    specs: {
      "Voltage": "14V",
      "Amperage": "65A",
      "Rotation": "Clockwise",
      "Pulley": "6-groove V-belt",
    },
    tags: ["alternator", "tractor electrical", "john deere alternator", "charging system"],
  },
  {
    id: 8,
    name: "Power Steering Cylinder",
    slug: "power-steering-cylinder",
    description: "Hydraulic power steering cylinder for Massey Ferguson and Ford/New Holland tractors. Provides smooth, responsive steering even in heavy field conditions.",
    shortDescription: "MF & Ford/New Holland",
    category: "Hydraulics",
    categorySlug: "hydraulics",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265-390, Ford 6600-7600",
    rating: 4,
    reviewCount: 12,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    featured: false,
    inStock: true,
    specs: {
      "Bore Diameter": "63.5mm",
      "Stroke": "203mm",
      "Rod Diameter": "31.75mm",
    },
    tags: ["power steering", "steering cylinder", "hydraulic steering", "massey ferguson steering"],
  },
];

export const reviews: Review[] = [
  {
    id: 1,
    author: "Oluwaseun Adebayo",
    role: "Farm Owner",
    location: "Ogun State",
    rating: 5,
    content: "Found the exact hydraulic pump I needed for my Massey Ferguson when no one else could help. Delivered to Abeokuta in just 2 days!",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: 2,
    author: "Chinedu Okonkwo",
    role: "Mechanic",
    location: "Lagos",
    rating: 4,
    content: "Their prices are very competitive compared to other suppliers in Lagos. I've saved over ₦200,000 on parts this year alone.",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b1a8?w=100&q=80",
  },
  {
    id: 3,
    author: "Emeka Nwosu",
    role: "Agricultural Engineer",
    location: "Anambra State",
    rating: 5,
    content: "The quality of parts from Unique Truth is consistently excellent. I always recommend them to farmers who need reliable tractor components.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
  {
    id: 4,
    author: "Fatima Aliyu",
    role: "Farm Manager",
    location: "Kano State",
    rating: 5,
    content: "Fast delivery nationwide is not a joke here. My engine parts arrived in Kano within 4 days. Exceptional service!",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
];

// All contact details are driven by environment variables.
// Copy .env.local.example → .env.local and fill in your real values.
const phone = process.env.NEXT_PUBLIC_PHONE || "—";
const whatsapp = process.env.NEXT_PUBLIC_WHATSAPP || "";          // e.g. +2348012345678
const email = process.env.NEXT_PUBLIC_EMAIL || "";
const address = process.env.NEXT_PUBLIC_ADDRESS || "";
const hours = process.env.NEXT_PUBLIC_HOURS || "Mon-Fri: 8am – 6pm, Sat: 9am – 4pm";

// Social-media handles (optional – leave blank to hide the icon)
const fbUrl       = process.env.NEXT_PUBLIC_FACEBOOK_URL || "";
const twitterUrl  = process.env.NEXT_PUBLIC_TWITTER_URL  || "";
const igUrl       = process.env.NEXT_PUBLIC_INSTAGRAM_URL || "";


const founded = "2018";


// Logo / favicon images (optional – falls back to emoji 🚜 if not supplied)
export const siteImages = {
  /** Local path like "/images/logo.png" or a full URL. Falls back to emoji. */
  logo:    "/logo.avif",
  /** Local path like "/images/favicon.png". Falls back to inline SVG tractor. */
  favicon: process.env.NEXT_PUBLIC_FAVICON_URL || "",
  /** Hero background – falls back to Unsplash tractor photo. */
  hero:    process.env.NEXT_PUBLIC_HERO_IMAGE_URL || "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1600&q=80",
  /** About-section warehouse photo – falls back to Unsplash. */
  about:   process.env.NEXT_PUBLIC_ABOUT_IMAGE_URL || "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
};

export const siteConfig = {
  name: "Unique Truth Auto Limited",
  tagline: "Your Trusted Source for Tractor Parts in Nigeria",
  description:
    "Nigeria's leading independent distributor of agricultural tractor spare parts and accessories. Premium quality engine parts, tires, hydraulics, and implements for John Deere, Massey Ferguson, New Holland, Kubota and more.",
  address,
  phone,
  /** Full international number with + prefix, e.g. +2348012345678 */
  whatsapp,
  email,
  hours,
  founded,
  yearsExperience: new Date().getFullYear() - parseInt(founded),
  stats: {
    partsInStock: "5,000+",
    satisfiedCustomers: "1,000+",
    statesCovered: "10",
  },
  socialMedia: {
    facebook:  fbUrl,
    twitter:   twitterUrl,
    instagram: igUrl,
    whatsapp:  whatsapp ? `https://wa.me/${whatsapp.replace("+", "")}` : "",
  },
  keywords: [
    "tractor parts Nigeria",
    "agricultural machinery parts Lagos",
    "John Deere parts Nigeria",
    "Massey Ferguson parts Nigeria",
    "New Holland tractor parts",
    "Kubota parts Nigeria",
    "tractor spare parts",
    "farm equipment parts Nigeria",
    "hydraulic parts tractor",
    "tractor tires Nigeria",
    "engine parts tractor Nigeria",
    "agricultural implements Nigeria",
    "tractor parts Nigeria",
    "buy tractor parts online Nigeria",
    "genuine tractor parts Nigeria",
  ],
};
