import { Product, Category, Review } from "@/types";
import { Settings, Circle, Droplets, Zap, GitMerge, Wheat } from "lucide-react";

export const categories: Category[] = [
  {
    id: 1,
    name: "Engine Parts",
    slug: "engine-parts",
    description: "High-performance engine components for all major tractor brands including John Deere, Massey Ferguson, New Holland, and Kubota. From pistons to fuel injectors.",
    productCount: 125,
    image: "https://images.unsplash.com/photo-1580983559367-0dc2f8934365?w=600&q=80",
    icon: "⚙️",
  },
  {
    id: 2,
    name: "Tires & Wheels",
    slug: "tires-wheels",
    description: "Agricultural tires and wheels for optimal traction in Nigerian terrain. Front and rear tractor tires, rims, and accessories.",
    productCount: 80,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    icon: "🔧",
  },
  {
    id: 3,
    name: "Hydraulics",
    slug: "hydraulics",
    description: "Complete hydraulic systems, pumps, cylinders, hoses, and control valves for agricultural machinery and tractors.",
    productCount: 65,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    icon: "💧",
  },
  {
    id: 4,
    name: "Electrical",
    slug: "electrical",
    description: "Alternators, starters, batteries, wiring harnesses, and electronic control modules for modern and classic tractors.",
    productCount: 90,
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
    icon: "⚡",
  },
  {
    id: 5,
    name: "Hydraulic Systems",
    slug: "hydraulic-systems",
    description: "Complete hydraulic lift assemblies, 3-point hitch components, and power steering systems.",
    productCount: 45,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    icon: "🔩",
  },
  {
    id: 6,
    name: "Implements",
    slug: "implements",
    description: "Ploughs, disc harrows, cultivators, seeders, and other agricultural implements for Nigerian farming operations.",
    productCount: 55,
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    icon: "🌾",
  },
];


// export const products: Product[] = [
//   {
//     id: 1,
//     name: "Diesel Engine Oil Filter",
//     slug: "diesel-engine-oil-filter",
//     description: "Premium diesel engine oil filter compatible with John Deere and Massey Ferguson tractors. Ensures clean oil circulation and extends engine life. Meets OEM specifications for optimal performance in Nigerian agricultural conditions.",
//     shortDescription: "Compatible with John Deere, Massey Ferguson",
//     category: "Engine Parts",
//     categorySlug: "engine-parts",
//     brand: "Kubota / OEM Compatible",
//     compatibility: "John Deere 5055E, 5075E; Massey Ferguson 265, 275, 290",
//     rating: 4.5,
//     reviewCount: 24,
//     badge: "Best Seller",
//     image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80",
//     featured: true,
//     inStock: true,
//     specs: {
//       "Filter Type": "Full-flow Oil Filter",
//       "Thread Size": "3/4-16 UNF",
//       "Height": "140mm",
//       "Outside Diameter": "96mm",
//       "Bypass Valve": "Yes",
//     },
//     tags: ["oil filter", "engine filter", "john deere parts", "massey ferguson parts", "diesel engine"],
//   },
//   {
//     id: 2,
//     name: "Rear Tractor Tire 13.6-28",
//     slug: "rear-tractor-tire-13-6-28",
//     description: "Heavy-duty rear tractor tire size 13.6-28 suitable for 50-75HP tractors. Deep lug pattern provides excellent traction on Nigerian farm terrain including wet and muddy conditions.",
//     shortDescription: "Fits most 50-75HP tractors",
//     category: "Tires & Wheels",
//     categorySlug: "tires-wheels",
//     brand: "BKT / Equivalent",
//     compatibility: "Most 50-75HP utility tractors",
//     rating: 5,
//     reviewCount: 37,
//     badge: "New Arrival",
//     image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
//     featured: true,
//     inStock: true,
//     specs: {
//       "Size": "13.6-28",
//       "Ply Rating": "8PR",
//       "Pattern": "R-1 Agricultural",
//       "Load Index": "116A8",
//       "Speed Symbol": "A8",
//     },
//     tags: ["tractor tire", "rear tire", "agricultural tire", "farm tire", "13.6-28"],
//   },
//   {
//     id: 3,
//     name: "Hydraulic Pump Assembly",
//     slug: "hydraulic-pump-assembly",
//     description: "Complete hydraulic pump assembly for John Deere 5055D and 5060E tractors. Delivers consistent hydraulic pressure for lift systems, power steering, and implement control. Direct replacement with no modification required.",
//     shortDescription: "John Deere 5055D, 5060E",
//     category: "Hydraulics",
//     categorySlug: "hydraulics",
//     brand: "OEM Compatible",
//     compatibility: "John Deere 5055D, 5060E, 5065E",
//     rating: 4.5,
//     reviewCount: 18,
//     badge: "Top Rated",
//     image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
//     featured: true,
//     inStock: true,
//     specs: {
//       "Flow Rate": "32 L/min",
//       "Operating Pressure": "200 bar",
//       "Drive Type": "Gear Drive",
//       "Port Size": "3/4\" BSP",
//     },
//     tags: ["hydraulic pump", "john deere hydraulics", "tractor hydraulics", "pump assembly"],
//   },
//   {
//     id: 4,
//     name: "Plough Implement",
//     slug: "plough-implement",
//     description: "Heavy-duty disc plough with universal 3-point hitch attachment. Ideal for primary tillage in Nigerian soil conditions. Adjustable working depth and disc angle for various crop types.",
//     shortDescription: "Universal 3-point hitch",
//     category: "Implements",
//     categorySlug: "implements",
//     brand: "Fieldking",
//     compatibility: "Universal 3-point hitch, Cat I & II",
//     rating: 4,
//     reviewCount: 22,
//     badge: "Best Seller",
//     image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
//     featured: true,
//     inStock: true,
//     specs: {
//       "Type": "Disc Plough",
//       "Number of Discs": "3",
//       "Disc Diameter": "610mm",
//       "Working Depth": "200-350mm",
//       "Hitch Type": "Cat I & II 3-point",
//     },
//     tags: ["plough", "disc plough", "farm implement", "tillage", "agricultural implement"],
//   },
//   {
//     id: 5,
//     name: "Front Tractor Tire 6.00-16",
//     slug: "front-tractor-tire-6-00-16",
//     description: "Quality front tractor tire size 6.00-16 for utility tractors. Ribbed pattern for smooth steering and road transport. Compatible with most utility tractors used across Nigeria.",
//     shortDescription: "Fits most utility tractors",
//     category: "Tires & Wheels",
//     categorySlug: "tires-wheels",
//     brand: "BKT / Equivalent",
//     compatibility: "Most utility tractors with F2 front axle",
//     rating: 4.5,
//     reviewCount: 15,
//     image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
//     featured: true,
//     inStock: true,
//     specs: {
//       "Size": "6.00-16",
//       "Ply Rating": "6PR",
//       "Pattern": "F-2 Ribbed",
//     },
//     tags: ["front tire", "tractor tire", "utility tractor tire", "6.00-16"],
//   },
//   {
//     id: 6,
//     name: "Engine Gasket Set",
//     slug: "engine-gasket-set",
//     description: "Complete engine gasket set for Massey Ferguson 265 and 275 tractors. Includes head gasket, valve cover gasket, intake/exhaust manifold gaskets, and all necessary seals. Premium materials for long-lasting performance.",
//     shortDescription: "Massey Ferguson 265, 275",
//     category: "Engine Parts",
//     categorySlug: "engine-parts",
//     brand: "OEM Compatible",
//     compatibility: "Massey Ferguson 265, 275, 290",
//     rating: 5,
//     reviewCount: 29,
//     badge: "New Arrival",
//     image: "https://images.unsplash.com/photo-1580983559367-0dc2f8934365?w=600&q=80",
//     featured: true,
//     inStock: true,
//     specs: {
//       "Contents": "Full Engine Gasket Set",
//       "Gaskets Included": "28 pieces",
//       "Material": "Multi-layer Steel / Graphite",
//     },
//     tags: ["gasket set", "engine gasket", "massey ferguson parts", "head gasket", "engine rebuild"],
//   },
//   {
//     id: 7,
//     name: "Alternator 14V 65A",
//     slug: "alternator-14v-65a",
//     description: "Heavy-duty alternator for John Deere and New Holland tractors. Provides reliable charging for all electrical systems. Direct bolt-on replacement with no wiring modifications needed.",
//     shortDescription: "John Deere, New Holland compatible",
//     category: "Electrical",
//     categorySlug: "electrical",
//     brand: "Bosch Compatible",
//     compatibility: "John Deere 5000 series, New Holland TD series",
//     rating: 4.5,
//     reviewCount: 19,
//     image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
//     featured: false,
//     inStock: true,
//     specs: {
//       "Voltage": "14V",
//       "Amperage": "65A",
//       "Rotation": "Clockwise",
//       "Pulley": "6-groove V-belt",
//     },
//     tags: ["alternator", "tractor electrical", "john deere alternator", "charging system"],
//   },
//   {
//     id: 8,
//     name: "Power Steering Cylinder",
//     slug: "power-steering-cylinder",
//     description: "Hydraulic power steering cylinder for Massey Ferguson and Ford/New Holland tractors. Provides smooth, responsive steering even in heavy field conditions.",
//     shortDescription: "MF & Ford/New Holland",
//     category: "Hydraulics",
//     categorySlug: "hydraulics",
//     brand: "OEM Compatible",
//     compatibility: "Massey Ferguson 265-390, Ford 6600-7600",
//     rating: 4,
//     reviewCount: 12,
//     image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
//     featured: false,
//     inStock: true,
//     specs: {
//       "Bore Diameter": "63.5mm",
//       "Stroke": "203mm",
//       "Rod Diameter": "31.75mm",
//     },
//     tags: ["power steering", "steering cylinder", "hydraulic steering", "massey ferguson steering"],
//   },
// ];


export const products: Product[] = [
  // ─── ENGINE RINGS ─────────────────────────────────────────────────────────

  {
    id: 1,
    name: "Engine Rings – 260",
    slug: "engine-rings-260",
    description: "Premium engine piston rings for Massey Ferguson 260 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 4.5,
    reviewCount: 18,
    badge: "Best Seller",
    image: "engine-rings.jpeg",
    featured: true,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "260",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 260", "compression rings"],
  },
  {
    id: 2,
    name: "Engine Rings – 265",
    slug: "engine-rings-265",
    description: "Premium engine piston rings for Massey Ferguson 265 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 4.5,
    reviewCount: 21,
    badge: "Best Seller",
    image: "engine-rings.jpeg",
    featured: true,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "265",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 265", "compression rings"],
  },
  {
    id: 3,
    name: "Engine Rings – 375",
    slug: "engine-rings-375",
    description: "Premium engine piston rings for Massey Ferguson 375 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 4.5,
    reviewCount: 14,
    image: "engine-rings.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "375",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 375", "compression rings"],
  },
  {
    id: 4,
    name: "Engine Rings – 135",
    slug: "engine-rings-135",
    description: "Premium engine piston rings for Massey Ferguson 135 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 4.5,
    reviewCount: 16,
    image: "engine-rings.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "135",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 135", "compression rings"],
  },
  {
    id: 5,
    name: "Engine Rings – 290",
    slug: "engine-rings-290",
    description: "Premium engine piston rings for Massey Ferguson 290 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 4.5,
    reviewCount: 19,
    image: "engine-rings.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "290",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 290", "compression rings"],
  },
  {
    id: 6,
    name: "Engine Rings – 590",
    slug: "engine-rings-590",
    description: "Premium engine piston rings for Massey Ferguson 590 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 4.5,
    reviewCount: 11,
    image: "engine-rings.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "590",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 590", "compression rings"],
  },
  {
    id: 7,
    name: "Engine Rings – 435",
    slug: "engine-rings-435",
    description: "Premium engine piston rings for Massey Ferguson 435 tractors. Engineered for precise fit and optimal compression. Resists wear and maintains oil control under demanding Nigerian farm conditions.",
    shortDescription: "Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 4.5,
    reviewCount: 13,
    image: "engine-rings.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Type": "Compression & Oil Control Ring Set",
      "Material": "Cast Iron / Chrome Faced",
      "Series": "435",
      "Finish": "Phosphate coated",
      "OEM Standard": "Yes",
    },
    tags: ["engine rings", "piston rings", "massey ferguson 435", "compression rings"],
  },

  // ─── ENGINE PISTONS ───────────────────────────────────────────────────────

  {
    id: 8,
    name: "Engine Pistons – 260",
    slug: "engine-pistons-260",
    description: "Heavy-duty engine pistons for Massey Ferguson 260 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 4.5,
    reviewCount: 15,
    image: "/engine-pistons.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "260",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 260", "tractor piston", "piston kit"],
  },
  {
    id: 9,
    name: "Engine Pistons – 265",
    slug: "engine-pistons-265",
    description: "Heavy-duty engine pistons for Massey Ferguson 265 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 4.5,
    reviewCount: 22,
    badge: "Best Seller",
    image: "/engine-pistons.jpeg",
    featured: true,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "265",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 265", "tractor piston", "piston kit"],
  },
  {
    id: 10,
    name: "Engine Pistons – 375",
    slug: "engine-pistons-375",
    description: "Heavy-duty engine pistons for Massey Ferguson 375 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 4.5,
    reviewCount: 17,
    image: "/engine-pistons.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "375",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 375", "tractor piston", "piston kit"],
  },
  {
    id: 11,
    name: "Engine Pistons – 135",
    slug: "engine-pistons-135",
    description: "Heavy-duty engine pistons for Massey Ferguson 135 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 4.5,
    reviewCount: 20,
    image: "/engine-pistons.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "135",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 135", "tractor piston", "piston kit"],
  },
  {
    id: 12,
    name: "Engine Pistons – 290",
    slug: "engine-pistons-290",
    description: "Heavy-duty engine pistons for Massey Ferguson 290 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 4.5,
    reviewCount: 18,
    image: "/engine-pistons.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "290",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 290", "tractor piston", "piston kit"],
  },
  {
    id: 13,
    name: "Engine Pistons – 590",
    slug: "engine-pistons-590",
    description: "Heavy-duty engine pistons for Massey Ferguson 590 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 4.5,
    reviewCount: 10,
    image: "/engine-pistons.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "590",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 590", "tractor piston", "piston kit"],
  },
  {
    id: 14,
    name: "Engine Pistons – 435",
    slug: "engine-pistons-435",
    description: "Heavy-duty engine pistons for Massey Ferguson 435 tractors. Cast from high-grade aluminium alloy for excellent heat resistance and durability. Precision machined to OEM specifications ensuring direct fit without modification.",
    shortDescription: "Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 4.5,
    reviewCount: 12,
    image: "/engine-pistons.jpeg",
    featured: false,
    inStock: true,
    specs: {
      "Material": "Aluminium Alloy",
      "Pin Included": "Yes",
      "Series": "435",
      "Surface Treatment": "Tin-plated skirt",
      "OEM Standard": "Yes",
    },
    tags: ["engine piston", "massey ferguson 435", "tractor piston", "piston kit"],
  },

  // ─── ENGINE SLEEVE ────────────────────────────────────────────────────────

  {
    id: 15,
    name: "Engine Sleeve – 260",
    slug: "engine-sleeve-260",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 260 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 4.5,
    reviewCount: 13,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "260", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 260", "engine sleeve"],
  },
  {
    id: 16,
    name: "Engine Sleeve – 265",
    slug: "engine-sleeve-265",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 265 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 4.5,
    reviewCount: 16,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "265", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 265", "engine sleeve"],
  },
  {
    id: 17,
    name: "Engine Sleeve – 375",
    slug: "engine-sleeve-375",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 375 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 4.5,
    reviewCount: 11,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "375", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 375", "engine sleeve"],
  },
  {
    id: 18,
    name: "Engine Sleeve – 135",
    slug: "engine-sleeve-135",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 135 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 4.5,
    reviewCount: 14,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "135", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 135", "engine sleeve"],
  },
  {
    id: 19,
    name: "Engine Sleeve – 290",
    slug: "engine-sleeve-290",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 290 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 4.5,
    reviewCount: 12,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "290", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 290", "engine sleeve"],
  },
  {
    id: 20,
    name: "Engine Sleeve – 590",
    slug: "engine-sleeve-590",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 590 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 4.5,
    reviewCount: 9,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "590", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 590", "engine sleeve"],
  },
  {
    id: 21,
    name: "Engine Sleeve – 435",
    slug: "engine-sleeve-435",
    description: "High-quality wet cylinder sleeve/liner for Massey Ferguson 435 tractors. Made from centrifugally cast alloy iron for maximum wear resistance. Provides a precision bore surface for optimal piston and ring seating.",
    shortDescription: "Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 4.5,
    reviewCount: 10,
    image: "/engine-sleeve.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "435", "Surface Finish": "Plateau honed bore", "OEM Standard": "Yes" },
    tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 435", "engine sleeve"],
  },

  // ─── METAL AND MAIN BEARING ───────────────────────────────────────────────

  {
    id: 22,
    name: "Metal & Main Bearing – Std",
    slug: "metal-main-bearing-std",
    description: "Standard size connecting rod (metal) and main crankshaft bearing set for Massey Ferguson tractors. Tri-metal construction ensures excellent load capacity and durability. For use with standard (unworn) crankshaft journals.",
    shortDescription: "Standard size — All compatible MF series",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260, 265, 375, 135, 290, 590, 435",
    rating: 4.5,
    reviewCount: 24,
    badge: "Best Seller",
    image: "/metal-main-bearing.jpeg",
    featured: true,
    inStock: true,
    specs: { "Type": "Connecting Rod & Main Bearing Set", "Material": "Tri-metal (Steel-backed)", "Size": "Standard (Std)", "OEM Standard": "Yes" },
    tags: ["main bearing", "metal bearing", "standard bearing", "crankshaft bearing", "massey ferguson bearing"],
  },
  {
    id: 23,
    name: "Metal & Main Bearing – O10",
    slug: "metal-main-bearing-o10",
    description: "0.010\" oversize connecting rod (metal) and main crankshaft bearing set for Massey Ferguson tractors. For use with crankshafts reground to 0.010\" undersize.",
    shortDescription: "+0.010\" oversize — All compatible MF series",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260, 265, 375, 135, 290, 590, 435",
    rating: 4.5,
    reviewCount: 17,
    image: "/metal-main-bearing.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Connecting Rod & Main Bearing Set", "Material": "Tri-metal (Steel-backed)", "Size": "O/S 0.010\"", "OEM Standard": "Yes" },
    tags: ["main bearing", "metal bearing", "0.010 oversize bearing", "crankshaft bearing"],
  },
  {
    id: 24,
    name: "Metal & Main Bearing – O20",
    slug: "metal-main-bearing-o20",
    description: "0.020\" oversize connecting rod (metal) and main crankshaft bearing set for Massey Ferguson tractors. For use with crankshafts reground to 0.020\" undersize.",
    shortDescription: "+0.020\" oversize — All compatible MF series",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260, 265, 375, 135, 290, 590, 435",
    rating: 4.5,
    reviewCount: 15,
    image: "/metal-main-bearing.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Connecting Rod & Main Bearing Set", "Material": "Tri-metal (Steel-backed)", "Size": "O/S 0.020\"", "OEM Standard": "Yes" },
    tags: ["main bearing", "metal bearing", "0.020 oversize bearing", "crankshaft bearing"],
  },
  {
    id: 25,
    name: "Metal & Main Bearing – O30",
    slug: "metal-main-bearing-o30",
    description: "0.030\" oversize connecting rod (metal) and main crankshaft bearing set for Massey Ferguson tractors. For use with crankshafts reground to 0.030\" undersize.",
    shortDescription: "+0.030\" oversize — All compatible MF series",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260, 265, 375, 135, 290, 590, 435",
    rating: 4.5,
    reviewCount: 13,
    image: "/metal-main-bearing.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Connecting Rod & Main Bearing Set", "Material": "Tri-metal (Steel-backed)", "Size": "O/S 0.030\"", "OEM Standard": "Yes" },
    tags: ["main bearing", "metal bearing", "0.030 oversize bearing", "crankshaft bearing"],
  },
  {
    id: 26,
    name: "Metal & Main Bearing – O40",
    slug: "metal-main-bearing-o40",
    description: "0.040\" oversize connecting rod (metal) and main crankshaft bearing set for Massey Ferguson tractors. For use with crankshafts reground to 0.040\" undersize.",
    shortDescription: "+0.040\" oversize — All compatible MF series",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260, 265, 375, 135, 290, 590, 435",
    rating: 4.5,
    reviewCount: 11,
    image: "/metal-main-bearing.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Connecting Rod & Main Bearing Set", "Material": "Tri-metal (Steel-backed)", "Size": "O/S 0.040\"", "OEM Standard": "Yes" },
    tags: ["main bearing", "metal bearing", "0.040 oversize bearing", "crankshaft bearing"],
  },

  // ─── TOP GASKET ───────────────────────────────────────────────────────────

  {
    id: 27,
    name: "Top Gasket – 260",
    slug: "top-gasket-260",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 260 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 5,
    reviewCount: 19,
    image: "/top-gasket.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "260", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 260"],
  },
  {
    id: 28,
    name: "Top Gasket – 265",
    slug: "top-gasket-265",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 265 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 5,
    reviewCount: 27,
    badge: "Top Rated",
    image: "/top-gasket.jpeg",
    featured: true,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "265", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 265"],
  },
  {
    id: 29,
    name: "Top Gasket – 375",
    slug: "top-gasket-375",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 375 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 5,
    reviewCount: 14,
    image: "/top-gasket.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "375", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 375"],
  },
  {
    id: 30,
    name: "Top Gasket – 135",
    slug: "top-gasket-135",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 135 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 5,
    reviewCount: 21,
    image: "/top-gasket.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "135", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 135"],
  },
  {
    id: 31,
    name: "Top Gasket – 290",
    slug: "top-gasket-290",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 290 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 5,
    reviewCount: 18,
    image: "/top-gasket.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "290", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 290"],
  },
  {
    id: 32,
    name: "Top Gasket – 590",
    slug: "top-gasket-590",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 590 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 5,
    reviewCount: 10,
    image: "/top-gasket.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "590", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 590"],
  },
  {
    id: 33,
    name: "Top Gasket – 435",
    slug: "top-gasket-435",
    description: "Premium multi-layer steel cylinder head gasket for Massey Ferguson 435 tractors. Provides a reliable high-compression seal between the cylinder head and block, resisting blow-outs and coolant or oil leaks.",
    shortDescription: "Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 5,
    reviewCount: 12,
    image: "/top-gasket.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel (MLS)", "Series": "435", "OEM Standard": "Yes" },
    tags: ["top gasket", "head gasket", "massey ferguson 435"],
  },

  // ─── ENGINE VALVES ────────────────────────────────────────────────────────

  {
    id: 34,
    name: "Engine Valves – 260",
    slug: "engine-valves-260",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 260 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 4.5,
    reviewCount: 13,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "260", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 260"],
  },
  {
    id: 35,
    name: "Engine Valves – 265",
    slug: "engine-valves-265",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 265 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 4.5,
    reviewCount: 20,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "265", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 265"],
  },
  {
    id: 36,
    name: "Engine Valves – 375",
    slug: "engine-valves-375",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 375 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 4.5,
    reviewCount: 11,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "375", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 375"],
  },
  {
    id: 37,
    name: "Engine Valves – 135",
    slug: "engine-valves-135",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 135 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 4.5,
    reviewCount: 15,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "135", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 135"],
  },
  {
    id: 38,
    name: "Engine Valves – 290",
    slug: "engine-valves-290",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 290 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 4.5,
    reviewCount: 17,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "290", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 290"],
  },
  {
    id: 39,
    name: "Engine Valves – 590",
    slug: "engine-valves-590",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 590 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 4.5,
    reviewCount: 9,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "590", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 590"],
  },
  {
    id: 40,
    name: "Engine Valves – 435",
    slug: "engine-valves-435",
    description: "High-quality inlet and exhaust engine valves for Massey Ferguson 435 tractors. Manufactured from heat-resistant steel alloy to withstand extreme combustion temperatures and maintain tight sealing over extended service life.",
    shortDescription: "Inlet & Exhaust — Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 4.5,
    reviewCount: 11,
    image: "engine-valves.avif",
    featured: false,
    inStock: true,
    specs: { "Type": "Inlet & Exhaust Valves", "Material": "Heat-resistant Steel Alloy", "Series": "435", "OEM Standard": "Yes" },
    tags: ["engine valve", "inlet valve", "exhaust valve", "massey ferguson 435"],
  },

  // ─── ENGINE OIL SEAL ──────────────────────────────────────────────────────

  {
    id: 41,
    name: "Engine Oil Seal – 260",
    slug: "engine-oil-seal-260",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 260 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 4.5,
    reviewCount: 12,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "260", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 260"],
  },
  {
    id: 42,
    name: "Engine Oil Seal – 265",
    slug: "engine-oil-seal-265",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 265 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 4.5,
    reviewCount: 18,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "265", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 265"],
  },
  {
    id: 43,
    name: "Engine Oil Seal – 375",
    slug: "engine-oil-seal-375",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 375 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 4.5,
    reviewCount: 10,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "375", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 375"],
  },
  {
    id: 44,
    name: "Engine Oil Seal – 135",
    slug: "engine-oil-seal-135",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 135 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 4.5,
    reviewCount: 14,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "135", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 135"],
  },
  {
    id: 45,
    name: "Engine Oil Seal – 290",
    slug: "engine-oil-seal-290",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 290 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 4.5,
    reviewCount: 16,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "290", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 290"],
  },
  {
    id: 46,
    name: "Engine Oil Seal – 590",
    slug: "engine-oil-seal-590",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 590 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 4.5,
    reviewCount: 8,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "590", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 590"],
  },
  {
    id: 47,
    name: "Engine Oil Seal – 435",
    slug: "engine-oil-seal-435",
    description: "Heavy-duty front and rear crankshaft oil seals for Massey Ferguson 435 tractors. Made from high-grade nitrile rubber with a metal casing for secure press-fit installation. Prevents engine oil leaks at the crankshaft.",
    shortDescription: "Front & Rear — Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 4.5,
    reviewCount: 9,
    image: "/engine-oil-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Front & Rear Crankshaft Oil Seal", "Material": "Nitrile Rubber / Metal Casing", "Series": "435", "OEM Standard": "Yes" },
    tags: ["oil seal", "crankshaft seal", "massey ferguson 435"],
  },

  // ─── COMPLETE GASKET SET ──────────────────────────────────────────────────

  {
    id: 48,
    name: "Complete Gasket Set – 260",
    slug: "complete-gasket-set-260",
    description: "Full engine overhaul gasket set for Massey Ferguson 260 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 5,
    reviewCount: 16,
    image: "/complete-gasket-set.jpeg",
    featured: false,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "260", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 260", "engine rebuild"],
  },
  {
    id: 49,
    name: "Complete Gasket Set – 265",
    slug: "complete-gasket-set-265",
    description: "Full engine overhaul gasket set for Massey Ferguson 265 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 5,
    reviewCount: 28,
    badge: "Best Seller",
    image: "/complete-gasket-set.jpeg",
    featured: true,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "265", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 265", "engine rebuild"],
  },
  {
    id: 50,
    name: "Complete Gasket Set – 375",
    slug: "complete-gasket-set-375",
    description: "Full engine overhaul gasket set for Massey Ferguson 375 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 5,
    reviewCount: 14,
    image: "/complete-gasket-set.jpeg",
    featured: false,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "375", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 375", "engine rebuild"],
  },
  {
    id: 51,
    name: "Complete Gasket Set – 135",
    slug: "complete-gasket-set-135",
    description: "Full engine overhaul gasket set for Massey Ferguson 135 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 5,
    reviewCount: 22,
    image: "/complete-gasket-set.jpeg",
    featured: false,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "135", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 135", "engine rebuild"],
  },
  {
    id: 52,
    name: "Complete Gasket Set – 290",
    slug: "complete-gasket-set-290",
    description: "Full engine overhaul gasket set for Massey Ferguson 290 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 5,
    reviewCount: 19,
    image: "/complete-gasket-set.jpeg",
    featured: false,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "290", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 290", "engine rebuild"],
  },
  {
    id: 53,
    name: "Complete Gasket Set – 590",
    slug: "complete-gasket-set-590",
    description: "Full engine overhaul gasket set for Massey Ferguson 590 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 5,
    reviewCount: 10,
    image: "/complete-gasket-set.jpeg",
    featured: false,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "590", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 590", "engine rebuild"],
  },
  {
    id: 54,
    name: "Complete Gasket Set – 435",
    slug: "complete-gasket-set-435",
    description: "Full engine overhaul gasket set for Massey Ferguson 435 tractors. Includes all gaskets and seals required for a complete engine rebuild: head gasket, valve cover, intake/exhaust manifold, oil pan, front cover, rear main seal, and all O-rings.",
    shortDescription: "Full overhaul set — Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 5,
    reviewCount: 12,
    image: "/complete-gasket-set.jpeg",
    featured: false,
    inStock: true,
    specs: { "Contents": "Full Engine Overhaul Gasket Set", "Gaskets Included": "30+ pieces", "Material": "MLS / Graphite / Nitrile", "Series": "435", "OEM Standard": "Yes" },
    tags: ["complete gasket set", "overhaul gasket", "massey ferguson 435", "engine rebuild"],
  },

  // ─── ENGINE VALVE SEAL ────────────────────────────────────────────────────

  {
    id: 55,
    name: "Engine Valve Seal – 260",
    slug: "engine-valve-seal-260",
    description: "Precision valve stem seals for Massey Ferguson 260 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 260",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 260",
    rating: 4.5,
    reviewCount: 11,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "260", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 260"],
  },
  {
    id: 56,
    name: "Engine Valve Seal – 265",
    slug: "engine-valve-seal-265",
    description: "Precision valve stem seals for Massey Ferguson 265 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 265",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265",
    rating: 4.5,
    reviewCount: 17,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "265", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 265"],
  },
  {
    id: 57,
    name: "Engine Valve Seal – 375",
    slug: "engine-valve-seal-375",
    description: "Precision valve stem seals for Massey Ferguson 375 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 375",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 375",
    rating: 4.5,
    reviewCount: 9,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "375", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 375"],
  },
  {
    id: 58,
    name: "Engine Valve Seal – 135",
    slug: "engine-valve-seal-135",
    description: "Precision valve stem seals for Massey Ferguson 135 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 135",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 135",
    rating: 4.5,
    reviewCount: 13,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "135", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 135"],
  },
  {
    id: 59,
    name: "Engine Valve Seal – 290",
    slug: "engine-valve-seal-290",
    description: "Precision valve stem seals for Massey Ferguson 290 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 290",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 290",
    rating: 4.5,
    reviewCount: 14,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "290", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 290"],
  },
  {
    id: 60,
    name: "Engine Valve Seal – 590",
    slug: "engine-valve-seal-590",
    description: "Precision valve stem seals for Massey Ferguson 590 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 590",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 590",
    rating: 4.5,
    reviewCount: 8,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "590", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 590"],
  },
  {
    id: 61,
    name: "Engine Valve Seal – 435",
    slug: "engine-valve-seal-435",
    description: "Precision valve stem seals for Massey Ferguson 435 tractors. Manufactured from fluoroelastomer (FKM) to prevent oil from being drawn down the valve stem into the combustion chamber. Reduces oil consumption and blue exhaust smoke.",
    shortDescription: "Massey Ferguson 435",
    category: "Engine Parts",
    categorySlug: "engine-parts",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 435",
    rating: 4.5,
    reviewCount: 10,
    image: "/engine-valve-seal.jpeg",
    featured: false,
    inStock: true,
    specs: { "Type": "Valve Stem Seal", "Material": "Fluoroelastomer (FKM)", "Series": "435", "OEM Standard": "Yes" },
    tags: ["valve seal", "valve stem seal", "massey ferguson 435"],
  },

  // ─── TIRES & WHEELS ───────────────────────────────────────────────────────

  {
    id: 62,
    name: "Rear Tractor Tire 13.6-28",
    slug: "rear-tractor-tire-13-6-28",
    description: "Heavy-duty rear tractor tire size 13.6-28 suitable for 50-75HP tractors. Deep lug pattern provides excellent traction on Nigerian farm terrain including wet and muddy conditions.",
    shortDescription: "Fits most 50-75HP tractors",
    category: "Tires & Wheels",
    categorySlug: "tires-wheels",
    brand: "BKT / Equivalent",
    compatibility: "Most 50-75HP utility tractors",
    rating: 5,
    reviewCount: 37,
    badge: "New Arrival",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    featured: true,
    inStock: true,
    specs: { "Size": "13.6-28", "Ply Rating": "8PR", "Pattern": "R-1 Agricultural", "Load Index": "116A8", "Speed Symbol": "A8" },
    tags: ["tractor tire", "rear tire", "agricultural tire", "farm tire", "13.6-28"],
  },
  {
    id: 63,
    name: "Front Tractor Tire 6.00-16",
    slug: "front-tractor-tire-6-00-16",
    description: "Quality front tractor tire size 6.00-16 for utility tractors. Ribbed pattern for smooth steering and road transport. Compatible with most utility tractors used across Nigeria.",
    shortDescription: "Fits most utility tractors",
    category: "Tires & Wheels",
    categorySlug: "tires-wheels",
    brand: "BKT / Equivalent",
    compatibility: "Most utility tractors with F2 front axle",
    rating: 4.5,
    reviewCount: 15,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    featured: true,
    inStock: true,
    specs: { "Size": "6.00-16", "Ply Rating": "6PR", "Pattern": "F-2 Ribbed" },
    tags: ["front tire", "tractor tire", "utility tractor tire", "6.00-16"],
  },

  // ─── HYDRAULICS ───────────────────────────────────────────────────────────

  {
    id: 64,
    name: "Hydraulic Pump Assembly",
    slug: "hydraulic-pump-assembly",
    description: "Complete hydraulic pump assembly for John Deere 5055D and 5060E tractors. Delivers consistent hydraulic pressure for lift systems, power steering, and implement control. Direct replacement with no modification required.",
    shortDescription: "John Deere 5055D, 5060E",
    category: "Hydraulics",
    categorySlug: "hydraulics",
    brand: "OEM Compatible",
    compatibility: "John Deere 5055D, 5060E, 5065E",
    rating: 4.5,
    reviewCount: 18,
    badge: "Top Rated",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    featured: true,
    inStock: true,
    specs: { "Flow Rate": "32 L/min", "Operating Pressure": "200 bar", "Drive Type": "Gear Drive", "Port Size": "3/4\" BSP" },
    tags: ["hydraulic pump", "john deere hydraulics", "tractor hydraulics", "pump assembly"],
  },
  {
    id: 65,
    name: "Power Steering Cylinder",
    slug: "power-steering-cylinder",
    description: "Hydraulic power steering cylinder for Massey Ferguson and Ford/New Holland tractors. Provides smooth, responsive steering even in heavy field conditions.",
    shortDescription: "MF & Ford/New Holland",
    category: "Hydraulics",
    categorySlug: "hydraulics",
    brand: "OEM Compatible",
    compatibility: "Massey Ferguson 265-390, Ford 6600-7600",
    rating: 4,
    reviewCount: 12,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    featured: false,
    inStock: true,
    specs: { "Bore Diameter": "63.5mm", "Stroke": "203mm", "Rod Diameter": "31.75mm" },
    tags: ["power steering", "steering cylinder", "hydraulic steering", "massey ferguson steering"],
  },

  // ─── IMPLEMENTS ───────────────────────────────────────────────────────────

  {
    id: 66,
    name: "Plough Implement",
    slug: "plough-implement",
    description: "Heavy-duty disc plough with universal 3-point hitch attachment. Ideal for primary tillage in Nigerian soil conditions. Adjustable working depth and disc angle for various crop types.",
    shortDescription: "Universal 3-point hitch",
    category: "Implements",
    categorySlug: "implements",
    brand: "Fieldking",
    compatibility: "Universal 3-point hitch, Cat I & II",
    rating: 4,
    reviewCount: 22,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    featured: true,
    inStock: true,
    specs: { "Type": "Disc Plough", "Number of Discs": "3", "Disc Diameter": "610mm", "Working Depth": "200-350mm", "Hitch Type": "Cat I & II 3-point" },
    tags: ["plough", "disc plough", "farm implement", "tillage", "agricultural implement"],
  },

  // ─── ELECTRICAL ───────────────────────────────────────────────────────────

  {
    id: 67,
    name: "Alternator 14V 65A",
    slug: "alternator-14v-65a",
    description: "Heavy-duty alternator for John Deere and New Holland tractors. Provides reliable charging for all electrical systems. Direct bolt-on replacement with no wiring modifications needed.",
    shortDescription: "John Deere, New Holland compatible",
    category: "Electrical",
    categorySlug: "electrical",
    brand: "Bosch Compatible",
    compatibility: "John Deere 5000 series, New Holland TD series",
    rating: 4.5,
    reviewCount: 19,
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
    featured: false,
    inStock: true,
    specs: { "Voltage": "14V", "Amperage": "65A", "Rotation": "Clockwise", "Pulley": "6-groove V-belt" },
    tags: ["alternator", "tractor electrical", "john deere alternator", "charging system"],
  },
];


export const reviews: Review[] = [
  {
    id: 1,
    author: "Oluwaseun Adebayo",
    role: "Farm Owner",
    location: "Ogun State",
    rating: 5,
    content: "Found the exact hydraulic pump I needed for my Massey Ferguson when no one else could help. Delivered to Abeokuta in just 2 days!",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: 2,
    author: "Chinedu Okonkwo",
    role: "Mechanic",
    location: "Lagos",
    rating: 4,
    content: "Their prices are very competitive compared to other suppliers in Lagos. I've saved over ₦200,000 on parts this year alone.",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b1a8?w=100&q=80",
  },
  {
    id: 3,
    author: "Emeka Nwosu",
    role: "Agricultural Engineer",
    location: "Anambra State",
    rating: 5,
    content: "The quality of parts from Unique Truth is consistently excellent. I always recommend them to farmers who need reliable tractor components.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
  {
    id: 4,
    author: "Fatima Aliyu",
    role: "Farm Manager",
    location: "Kano State",
    rating: 5,
    content: "Fast delivery nationwide is not a joke here. My engine parts arrived in Kano within 4 days. Exceptional service!",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
];

// All contact details are driven by environment variables.
// Copy .env.local.example → .env.local and fill in your real values.
const phone = process.env.NEXT_PUBLIC_PHONE || "—";
const whatsapp = process.env.NEXT_PUBLIC_WHATSAPP || "";          // e.g. +2348012345678
const email = process.env.NEXT_PUBLIC_EMAIL || "";
const address = process.env.NEXT_PUBLIC_ADDRESS || "";
const hours = process.env.NEXT_PUBLIC_HOURS || "Mon-Fri: 8am – 6pm, Sat: 9am – 4pm";

// Social-media handles (optional – leave blank to hide the icon)
const fbUrl       = process.env.NEXT_PUBLIC_FACEBOOK_URL || "";
const twitterUrl  = process.env.NEXT_PUBLIC_TWITTER_URL  || "";
const igUrl       = process.env.NEXT_PUBLIC_INSTAGRAM_URL || "";


const founded = "2018";


// Logo / favicon images (optional – falls back to emoji 🚜 if not supplied)
export const siteImages = {
  /** Local path like "/images/logo.png" or a full URL. Falls back to emoji. */
  logo:    "/logo.avif",
  /** Local path like "/images/favicon.png". Falls back to inline SVG tractor. */
  favicon: process.env.NEXT_PUBLIC_FAVICON_URL || "",
  /** Hero background – falls back to Unsplash tractor photo. */
  hero:    process.env.NEXT_PUBLIC_HERO_IMAGE_URL || "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1600&q=80",
  /** About-section warehouse photo – falls back to Unsplash. */
  about:   process.env.NEXT_PUBLIC_ABOUT_IMAGE_URL || "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
};

export const siteConfig = {
  name: "Unique Truth Auto Limited",
  tagline: "Your Trusted Source for Tractor Parts in Nigeria",
  description:
    "Nigeria's leading independent distributor of agricultural tractor spare parts and accessories. Premium quality engine parts, tires, hydraulics, and implements for John Deere, Massey Ferguson, New Holland, Kubota and more.",
  address,
  phone,
  /** Full international number with + prefix, e.g. +2348012345678 */
  whatsapp,
  email,
  hours,
  founded,
  yearsExperience: new Date().getFullYear() - parseInt(founded),
  stats: {
    partsInStock: "5,000+",
    satisfiedCustomers: "1,000+",
    statesCovered: "10",
  },
  socialMedia: {
    facebook:  fbUrl,
    twitter:   twitterUrl,
    instagram: igUrl,
    whatsapp:  whatsapp ? `https://wa.me/${whatsapp.replace("+", "")}` : "",
  },
  keywords: [
    "tractor parts Nigeria",
    "agricultural machinery parts Lagos",
    "John Deere parts Nigeria",
    "Massey Ferguson parts Nigeria",
    "New Holland tractor parts",
    "Kubota parts Nigeria",
    "tractor spare parts",
    "farm equipment parts Nigeria",
    "hydraulic parts tractor",
    "tractor tires Nigeria",
    "engine parts tractor Nigeria",
    "agricultural implements Nigeria",
    "tractor parts Nigeria",
    "buy tractor parts online Nigeria",
    "genuine tractor parts Nigeria",
  ],
};
