import { Product, Category, Review } from "@/types";
import TractorIcon from "@/components/icons/Tractoricon";
import EngineIcon from "@/components/icons/Engineicon";
import HydraulicIcon from "@/components/icons/Hydraulicicon";
import TransmissionIcon from "@/components/icons/Transmissionicon";
import SuspensionIcon from "@/components/icons/Suspensionicon";
import BrakeIcon from "@/components/icons/Brakeicon";
import ElectricIcon from "@/components/icons/Electricicon";
import TractorPartIcon from "@/components/icons/Tractorparticon";
import ImplementIcon from "@/components/icons/Implementicon";


export const categories: Category[] = [
  {
    id: 1,
    name: "Tractors",
    slug: "tractors",
    description: "Brand new and certified pre-owned tractors — Fiat, Ford, Mahindra, New Holland, Sonalika, Steyr, Swaraj.",
    productCount: 17, 
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    icon: TractorIcon
  },
  { id: 2, 
    name: "Engine Parts", 
    slug: "engine-parts", 
    description: "Pistons, rings, sleeves, gaskets, bearings, pumps and all engine components.", 
    productCount: 80, 
    image: "https://images.unsplash.com/photo-1580983559367-0dc2f8934365?w=600&q=80",
    icon: EngineIcon
  },
  { id: 3, 
    name: "Hydraulics", 
    slug: "hydraulics", 
    description: "Hydraulic pumps, cylinders, hoses, valves, ram parts and linkage.",
    productCount: 50, 
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    icon: HydraulicIcon
  },
  { id: 4, 
    name: "Transmission", 
    slug: "transmission", 
    description: "Clutch kits, gears, shafts, bearings, washers and gearbox internals.",
    productCount: 40, 
    image: "https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=600&q=80",
    icon: TransmissionIcon
  },
  { id: 5, 
    name: "Steering & Suspension", 
    slug: "steering-suspension",
    description: "Steering boxes, cylinders, control units, pump nuts, pins, ball joints and tie rods.", 
    productCount: 20, 
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&q=80",
    icon: SuspensionIcon
  },
  { id: 6, 
    name: "Brakes", 
    slug: "brakes", 
    description: "Brake pads, shoes, drums, cylinders and linings.",
    productCount: 20, 
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80", 
    icon: BrakeIcon
  },
  { id: 7, 
    name: "Electrical", 
    slug: "electrical", 
    description: "Starter motors, alternators, dynamos, wiring harnesses, ignition switches and lights.",
    productCount: 20,
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80", 
    icon: ElectricIcon
  },
  { id: 8, 
    name: "Tractor Parts", 
    slug: "tractor-parts", 
    description: "Front axle, wheel hubs, rims, bolts, spindles, seats, top links and hitch parts.",
    productCount: 30,
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    icon: TractorPartIcon
  },
  { id: 9, 
    name: "Farm Implements", 
    slug: "farm-implements", 
    description: "Ploughs, ridgers and their replacement discs, hubs and frames.", 
    productCount: 6,
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    icon: ImplementIcon
  },
];


export const products: Product[] = [

  // ── TRACTORS ──────────────────────────────────────────────────────────────

  
  { id: 200, name: "Fiat 640", slug: "fiat-640", description: "The Fiat 640 is a robust 65HP utility tractor proven in Nigerian agricultural conditions. 4-cylinder diesel engine delivers reliable draft power for primary tillage, transport and PTO-driven implements. Parts are widely available across Nigeria.", shortDescription: "65HP — 4-cylinder diesel", category: "Tractors", categorySlug: "tractors", brand: "Fiat", compatibility: "Fiat 640", rating: 4.5, reviewCount: 12, image: "/Tractors/Fiat/640/Fiat 640.jpg", featured: true, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "65HP", "Transmission": "8F / 2R", "PTO": "540 RPM", "Lift Capacity": "2,500 kg", "Drive": "2WD" }, tags: ["fiat", "fiat 640", "65hp", "tractor"] },
  { id: 201, name: "Fiat 666", slug: "fiat-666", description: "The Fiat 666 is a dependable 70HP agricultural tractor with a strong track record on Nigerian farms. Robust 4-cylinder engine, durable gearbox and wide parts availability make it a trusted workhorse for row-crop and general-purpose farming.", shortDescription: "70HP — 4-cylinder diesel", category: "Tractors", categorySlug: "tractors", brand: "Fiat", compatibility: "Fiat 666", rating: 4.5, reviewCount: 10, image: "/Tractors/Fiat/666/Fiat-666.jpg", featured: false, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "70HP", "Transmission": "8F / 2R", "PTO": "540 RPM", "Lift Capacity": "2,800 kg", "Drive": "2WD" }, tags: ["fiat", "fiat 666", "70hp", "tractor"] },
  { id: 202, name: "Fiat 750", slug: "fiat-750", description: "The Fiat 750 is a medium-duty 75HP tractor suited to a wide range of Nigerian farming tasks — from ploughing heavy clay soils to powering threshers and water pumps. Known for simple, robust construction and straightforward maintenance.", shortDescription: "75HP — 4-cylinder diesel", category: "Tractors", categorySlug: "tractors", brand: "Fiat", compatibility: "Fiat 750", rating: 4.5, reviewCount: 8, image: "/Tractors/Fiat/750/fiat-750-tractor.webp", featured: false, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "75HP", "Transmission": "8F / 2R", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,000 kg", "Drive": "2WD" }, tags: ["fiat", "fiat 750", "75hp", "tractor"] },
  { id: 203, name: "Fiat 780", slug: "fiat-780", description: "The Fiat 780 delivers 80HP and is one of the more powerful Fiat models found in Nigerian agriculture. Suitable for heavy disc-ploughing, deep tillage and large-scale operations. Rugged construction ensures longevity in harsh field environments.", shortDescription: "80HP — 4-cylinder diesel", category: "Tractors", categorySlug: "tractors", brand: "Fiat", compatibility: "Fiat 780", rating: 4.5, reviewCount: 9, image: "/Tractors/Fiat/780/780.avif", featured: false, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "80HP", "Transmission": "8F / 2R", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,200 kg", "Drive": "2WD" }, tags: ["fiat", "fiat 780", "80hp", "tractor"] },
  { id: 204, name: "Fiat 80-66", slug: "fiat-8066", description: "The Fiat 80-66 is an 80HP tractor from the 66 series with enhanced hydraulics and improved operator controls. Popular in northern Nigeria for large-scale grain farming, combining power with modern hydraulic controls.", shortDescription: "80HP — 66 series", category: "Tractors", categorySlug: "tractors", brand: "Fiat", compatibility: "Fiat 80-66", rating: 4.5, reviewCount: 7, image: "/Tractors/Fiat/8066/Fiat-80-66.jpg", featured: false, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "80HP", "Transmission": "12F / 4R", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,500 kg", "Drive": "2WD / 4WD option" }, tags: ["fiat", "fiat 80-66", "80hp", "tractor"] },
  { id: 205, name: "Ford 5000", slug: "ford-5000", description: "The Ford 5000 is a classic 65HP utility tractor with a proven track record across decades of Nigerian farming. Simple hydraulics and wide spare parts availability make it one of the most popular choices for smallholder and medium-scale farmers.", shortDescription: "65HP — Classic utility tractor", category: "Tractors", categorySlug: "tractors", brand: "Ford", compatibility: "Ford 5000", rating: 5, reviewCount: 18, badge: "Best Seller", image: "/Tractors/Ford/5000/Ford-5000.webp", featured: true, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "65HP", "Transmission": "8F / 2R", "PTO": "540 RPM", "Lift Capacity": "2,500 kg", "Drive": "2WD" }, tags: ["ford", "ford 5000", "65hp", "tractor"] },
  { id: 206, name: "Ford 6600", slug: "ford-6600", description: "The Ford 6600 is a 75HP workhorse combining reliability with a user-friendly transmission and powerful hydraulic lift. Widely used across Nigeria for ploughing, ridging and transport.", shortDescription: "75HP — General purpose", category: "Tractors", categorySlug: "tractors", brand: "Ford", compatibility: "Ford 6600", rating: 4.5, reviewCount: 14, image: "/Tractors/Ford/6600/Ford-6600.jpg", featured: true, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "75HP", "Transmission": "8F / 2R", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,000 kg", "Drive": "2WD" }, tags: ["ford", "ford 6600", "75hp", "tractor"] },
  { id: 207, name: "Ford 6610", slug: "ford-6610", description: "The Ford 6610 is an 80HP upgraded version of the 6600 with improved hydraulics, enhanced operator controls and greater PTO power. A popular choice for medium-to-large Nigerian farms requiring high-output field performance.", shortDescription: "80HP — Enhanced hydraulics", category: "Tractors", categorySlug: "tractors", brand: "Ford", compatibility: "Ford 6610", rating: 4.5, reviewCount: 11, image: "/Tractors/Ford/6610/ford-6610.jpg", featured: false, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "80HP", "Transmission": "8F / 2R (or 16F / 4R)", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,200 kg", "Drive": "2WD / 4WD option" }, tags: ["ford", "ford 6610", "80hp", "tractor"] },
  { id: 208, name: "Mahindra 605", slug: "mahindra-605", description: "The Mahindra Novo 605 is a modern 60HP 4WD tractor designed for Nigerian farming conditions. Features a turbocharged diesel engine, 8-speed transmission and Category II 3-point linkage. Fuel-efficient and easy to maintain.", shortDescription: "60HP — 4WD turbocharged", category: "Tractors", categorySlug: "tractors", brand: "Mahindra", compatibility: "Mahindra 605", rating: 4.5, reviewCount: 9, image: "/Tractors/Mahindra/605/novo-605-mahindra-tractor.jpg", featured: false, inStock: true, specs: { "Engine": "3-cylinder turbocharged diesel", "Power": "60HP", "Transmission": "8F / 2R", "PTO": "540 RPM", "Lift Capacity": "2,000 kg", "Drive": "4WD" }, tags: ["mahindra", "mahindra 605", "60hp", "4wd", "tractor"] },
  { id: 209, name: "Mahindra 6005", slug: "mahindra-6005", description: "The Mahindra 6005 is a 60HP 2WD utility tractor offering an excellent combination of power, economy and build quality. Suited to smallholder and medium-scale Nigerian farmers needing a dependable machine for tillage, planting and haulage.", shortDescription: "60HP — 2WD utility", category: "Tractors", categorySlug: "tractors", brand: "Mahindra", compatibility: "Mahindra 6005", rating: 4.5, reviewCount: 8, image: "/Tractors/Mahindra/6005/6005.jpeg", featured: false, inStock: true, specs: { "Engine": "3-cylinder diesel", "Power": "60HP", "Transmission": "8F / 2R", "PTO": "540 RPM", "Lift Capacity": "1,800 kg", "Drive": "2WD" }, tags: ["mahindra", "mahindra 6005", "60hp", "tractor"] },
  { id: 210, name: "Mahindra 6060", slug: "mahindra-6060", description: "The Mahindra 6060 is a powerful 60HP 4WD tractor built for demanding Nigerian soil conditions. Strong hydraulic system, comfortable operator platform and low fuel consumption make it well-suited to medium and large-scale operations.", shortDescription: "60HP — 4WD heavy-duty", category: "Tractors", categorySlug: "tractors", brand: "Mahindra", compatibility: "Mahindra 6060", rating: 4.5, reviewCount: 10, image: "/Tractors/Mahindra/6060/6060-on-white.jpg", featured: false, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "60HP", "Transmission": "12F / 3R", "PTO": "540 / 1000 RPM", "Lift Capacity": "2,200 kg", "Drive": "4WD" }, tags: ["mahindra", "mahindra 6060", "60hp", "4wd", "tractor"] },
  { id: 211, name: "New Holland", slug: "new-holland", description: "New Holland agricultural tractors are renowned worldwide for reliability, comfort and productivity. Models available for Nigerian farming range from 55HP to 90HP with advanced hydraulics, spacious cabs and excellent fuel efficiency.", shortDescription: "55–90HP — Advanced hydraulics", category: "Tractors", categorySlug: "tractors", brand: "New Holland", compatibility: "New Holland series", rating: 5, reviewCount: 16, badge: "Top Rated", image: "/Tractors/New Holland/New holland.webp", featured: true, inStock: true, specs: { "Engine": "4-cylinder diesel", "Power": "55–90HP", "Transmission": "8F / 2R to 12F / 12R", "PTO": "540 / 1000 RPM", "Lift Capacity": "Up to 4,000 kg", "Drive": "2WD / 4WD" }, tags: ["new holland", "55hp", "90hp", "tractor"] },
  { id: 212, name: "Sonalika DI 75", slug: "sonalika-di-75", description: "The Sonalika DI 75 is a 75HP direct-injection diesel tractor built for heavy-duty applications. Powerful engine, robust transmission and large hydraulic lift capacity make it suitable for deep ploughing, ridging and large PTO implements.", shortDescription: "75HP — Direct injection diesel", category: "Tractors", categorySlug: "tractors", brand: "Sonalika", compatibility: "Sonalika DI 75", rating: 4.5, reviewCount: 7, image: "/Tractors/Sonalika/DI 75/Sonalika Tractors DI 75.jpeg", featured: false, inStock: true, specs: { "Engine": "4-cylinder direct injection diesel", "Power": "75HP", "Transmission": "8F / 2R", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,200 kg", "Drive": "2WD / 4WD option" }, tags: ["sonalika", "sonalika di 75", "75hp", "tractor"] },
  { id: 213, name: "Steyr 768", slug: "steyr-768", description: "The Steyr 768 is a premium 68HP Austrian-engineered tractor with outstanding build quality and operator ergonomics. Turbocharged diesel engine, synchronised transmission and full hydraulic system — well regarded by Nigerian farm managers for durability.", shortDescription: "68HP — Austrian engineering", category: "Tractors", categorySlug: "tractors", brand: "Steyr", compatibility: "Steyr 768", rating: 4.5, reviewCount: 9, image: "/Tractors/Steyr/768/768.jpg", featured: false, inStock: true, specs: { "Engine": "4-cylinder turbocharged diesel", "Power": "68HP", "Transmission": "12F / 4R", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,000 kg", "Drive": "2WD / 4WD" }, tags: ["steyr", "steyr 768", "68hp", "tractor"] },
  { id: 214, name: "Steyr 8075", slug: "steyr-8075", description: "The Steyr 8075 is a high-performance 75HP tractor from the premium 8000 series. Full synchromesh transmission, powerful rear linkage and front-wheel assist deliver superior fieldwork productivity on medium and large Nigerian farms.", shortDescription: "75HP — 8000 series", category: "Tractors", categorySlug: "tractors", brand: "Steyr", compatibility: "Steyr 8075", rating: 5, reviewCount: 11, badge: "Top Rated", image: "/Tractors/Steyr/8075/8075.jpg", featured: true, inStock: true, specs: { "Engine": "4-cylinder turbocharged diesel", "Power": "75HP", "Transmission": "12F / 4R synchromesh", "PTO": "540 / 1000 RPM", "Lift Capacity": "3,500 kg", "Drive": "4WD" }, tags: ["steyr", "steyr 8075", "75hp", "tractor"] },
  { id: 215, name: "Steyr 8120", slug: "steyr-8120", description: "The Steyr 8120 is the flagship 120HP model from the Steyr 8000 series — one of the most powerful tractors available for large-scale Nigerian farming. Turbocharged engine, electronic draft control and spacious cab for commercial farm operations.", shortDescription: "120HP — Flagship commercial tractor", category: "Tractors", categorySlug: "tractors", brand: "Steyr", compatibility: "Steyr 8120", rating: 5, reviewCount: 8, badge: "New Arrival", image: "/Tractors/Steyr/8120/8120.jpg", featured: true, inStock: true, specs: { "Engine": "6-cylinder turbocharged diesel", "Power": "120HP", "Transmission": "16F / 8R", "PTO": "540 / 1000 RPM", "Lift Capacity": "5,500 kg", "Drive": "4WD" }, tags: ["steyr", "steyr 8120", "120hp", "tractor"] },
  { id: 216, name: "Swaraj Tractor", slug: "swaraj-tractor", description: "Swaraj tractors are Indian-engineered machines built for value, reliability and ease of maintenance — qualities that resonate with Nigerian smallholder and medium-scale farmers. Available in 35–65HP configurations for ridging, planting and farm transport.", shortDescription: "35–65HP — Value & reliability", category: "Tractors", categorySlug: "tractors", brand: "Swaraj", compatibility: "Swaraj series", rating: 4.5, reviewCount: 6, image: "/Tractors/Swaraj/Swaraj Tractor.jpeg", featured: false, inStock: true, specs: { "Engine": "2–4 cylinder diesel", "Power": "35–65HP", "Transmission": "8F / 2R", "PTO": "540 RPM", "Lift Capacity": "Up to 2,000 kg", "Drive": "2WD / 4WD" }, tags: ["swaraj", "35hp", "65hp", "tractor"] },

  // ── ENGINE RINGS ──────────────────────────────────────────────────────────

  { id: 1, name: "Engine Rings – 135", slug: "engine-rings-135", description: "Premium piston ring set for Massey Ferguson 135. Cast iron with chrome-faced top ring for maximum wear resistance and oil control.", shortDescription: "Massey Ferguson 135", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135", rating: 4.5, reviewCount: 16, image: "/Tractor parts/Engine/Ring/135/Piston ring set.webp", featured: false, inStock: true, specs: { "Type": "Compression & Oil Control Ring Set", "Material": "Cast Iron / Chrome Faced", "Series": "135" }, tags: ["engine rings", "piston rings", "massey ferguson 135"] },
  { id: 2, name: "Engine Rings – 165", slug: "engine-rings-165", description: "Premium piston ring set for Massey Ferguson 165. Cast iron with chrome-faced top ring for maximum wear resistance and oil control.", shortDescription: "Massey Ferguson 165", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 165", rating: 4.5, reviewCount: 15, image: "/Tractor parts/Engine/Ring/165/Piston ring set.webp", featured: false, inStock: true, specs: { "Type": "Compression & Oil Control Ring Set", "Material": "Cast Iron / Chrome Faced", "Series": "165" }, tags: ["engine rings", "piston rings", "massey ferguson 165"] },
  { id: 3, name: "Engine Rings – 265", slug: "engine-rings-265", description: "Premium piston ring set for Massey Ferguson 265. Cast iron with chrome-faced top ring for maximum wear resistance and oil control.", shortDescription: "Massey Ferguson 265", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 21, badge: "Best Seller", image: "/Tractor parts/Engine/Ring/265/Piston ring set.webp", featured: true, inStock: true, specs: { "Type": "Compression & Oil Control Ring Set", "Material": "Cast Iron / Chrome Faced", "Series": "265" }, tags: ["engine rings", "piston rings", "massey ferguson 265"] },
  { id: 4, name: "Engine Rings – 375", slug: "engine-rings-375", description: "Premium piston ring set for Massey Ferguson 375. Cast iron with chrome-faced top ring for maximum wear resistance and oil control.", shortDescription: "Massey Ferguson 375", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 14, image: "/Tractor parts/Engine/Ring/375/Piston ring set.webp", featured: false, inStock: true, specs: { "Type": "Compression & Oil Control Ring Set", "Material": "Cast Iron / Chrome Faced", "Series": "375" }, tags: ["engine rings", "piston rings", "massey ferguson 375"] },
  { id: 5, name: "Engine Rings – 435", slug: "engine-rings-435", description: "Premium piston ring set for Massey Ferguson 435. Cast iron with chrome-faced top ring for maximum wear resistance and oil control.", shortDescription: "Massey Ferguson 435", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 435", rating: 4.5, reviewCount: 13, image: "/Tractor parts/Engine/Ring/435/Piston ring set.webp", featured: false, inStock: true, specs: { "Type": "Compression & Oil Control Ring Set", "Material": "Cast Iron / Chrome Faced", "Series": "435" }, tags: ["engine rings", "piston rings", "massey ferguson 435"] },
  { id: 6, name: "Engine Rings – 595", slug: "engine-rings-595", description: "Premium piston ring set for Massey Ferguson 595. Cast iron with chrome-faced top ring for maximum wear resistance and oil control.", shortDescription: "Massey Ferguson 595", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 595", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Engine/Ring/595/Piston ring set.webp", featured: false, inStock: true, specs: { "Type": "Compression & Oil Control Ring Set", "Material": "Cast Iron / Chrome Faced", "Series": "595" }, tags: ["engine rings", "piston rings", "massey ferguson 595"] },

  // ── ENGINE PISTONS ────────────────────────────────────────────────────────

  { id: 10, name: "Engine Pistons – 265", slug: "engine-pistons-265", description: "Heavy-duty aluminium alloy piston for Massey Ferguson 265. Precision machined to OEM specifications for direct fit. Includes gudgeon pin.", shortDescription: "Massey Ferguson 265", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 22, badge: "Best Seller", image: "/Tractor parts/Engine/Piston/265/Piston 265.webp", featured: true, inStock: true, specs: { "Material": "Aluminium Alloy", "Pin Included": "Yes", "Series": "265" }, tags: ["engine piston", "massey ferguson 265"] },
  { id: 11, name: "Engine Pistons – 375", slug: "engine-pistons-375", description: "Heavy-duty aluminium alloy piston for Massey Ferguson 375. Precision machined to OEM specifications for direct fit. Includes gudgeon pin.", shortDescription: "Massey Ferguson 375", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 17, image: "/Tractor parts/Engine/Piston/375/Piston 375.webp", featured: false, inStock: true, specs: { "Material": "Aluminium Alloy", "Pin Included": "Yes", "Series": "375" }, tags: ["engine piston", "massey ferguson 375"] },

  // ── ENGINE SLEEVES ────────────────────────────────────────────────────────

  { id: 20, name: "Engine Sleeve – 135", slug: "engine-sleeve-135", description: "Wet cylinder liner for Massey Ferguson 135. Centrifugally cast alloy iron for maximum wear resistance with a plateau-honed bore for optimal ring seating.", shortDescription: "Massey Ferguson 135", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135", rating: 4.5, reviewCount: 14, image: "/Tractor parts/Engine/Sleeve/135/Sleeve (Cylinder Liner) – 135.jpeg", featured: false, inStock: true, specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "135" }, tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 135"] },
  { id: 21, name: "Engine Sleeve – 265", slug: "engine-sleeve-265", description: "Wet cylinder liner for Massey Ferguson 265. Centrifugally cast alloy iron for maximum wear resistance with a plateau-honed bore for optimal ring seating.", shortDescription: "Massey Ferguson 265", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 16, image: "/Tractor parts/Engine/Sleeve/265/Sleeve (Cylinder Liner) – 265.jpeg", featured: false, inStock: true, specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "265" }, tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 265"] },
  { id: 22, name: "Engine Sleeve – 290", slug: "engine-sleeve-290", description: "Wet cylinder liner for Massey Ferguson 290. Centrifugally cast alloy iron for maximum wear resistance with plateau-honed bore.", shortDescription: "Massey Ferguson 290", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 290", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Engine/Sleeve/290/Sleeve (Cylinder Liner) – 290.jpeg", featured: false, inStock: true, specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "290" }, tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 290"] },
  { id: 23, name: "Engine Sleeve – 375", slug: "engine-sleeve-375", description: "Wet cylinder liner for Massey Ferguson 375. Centrifugally cast alloy iron for maximum wear resistance with plateau-honed bore.", shortDescription: "Massey Ferguson 375", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Engine/Sleeve/375/Sleeve (Cylinder Liner) – 375.jpeg", featured: false, inStock: true, specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "375" }, tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 375"] },
  { id: 24, name: "Engine Sleeve – 435", slug: "engine-sleeve-435", description: "Wet cylinder liner for Massey Ferguson 435. Centrifugally cast alloy iron for maximum wear resistance with plateau-honed bore.", shortDescription: "Massey Ferguson 435", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 435", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Engine/Sleeve/435/Sleeve (Cylinder Liner) – 435.jpeg", featured: false, inStock: true, specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "435" }, tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 435"] },
  { id: 25, name: "Engine Sleeve – 590", slug: "engine-sleeve-590", description: "Wet cylinder liner for Massey Ferguson 590. Centrifugally cast alloy iron for maximum wear resistance with plateau-honed bore.", shortDescription: "Massey Ferguson 590", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 590", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Engine/Sleeve/590/Sleeve (Cylinder Liner) – 590.jpeg", featured: false, inStock: true, specs: { "Type": "Wet Cylinder Liner", "Material": "Centrifugally Cast Alloy Iron", "Series": "590" }, tags: ["cylinder sleeve", "cylinder liner", "massey ferguson 590"] },

  // ── MAIN BEARINGS ─────────────────────────────────────────────────────────

  { id: 30, name: "Main Bearing – Std", slug: "main-bearing-std", description: "Standard size connecting rod and main crankshaft bearing set for Massey Ferguson tractors. Tri-metal construction for excellent load capacity. For use with standard unworn crankshaft journals.", shortDescription: "Standard size — All compatible MF", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 435, 590", rating: 4.5, reviewCount: 24, badge: "Best Seller", image: "/Tractor parts/Engine/Main Bearing & Metal/STD/main bearing standard.jpg", featured: true, inStock: true, specs: { "Type": "Con Rod & Main Bearing Set", "Material": "Tri-metal", "Size": "Standard" }, tags: ["main bearing", "crankshaft bearing", "standard"] },
  { id: 31, name: "Main Bearing – O10", slug: "main-bearing-o10", description: "0.010\" oversize connecting rod and main crankshaft bearing set for Massey Ferguson tractors. For crankshafts reground to 0.010\" undersize.", shortDescription: "0.010\" oversize — All compatible MF", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 435, 590", rating: 4.5, reviewCount: 17, image: "/Tractor parts/Engine/Main Bearing & Metal/010/main bearing 010.jpg", featured: false, inStock: true, specs: { "Type": "Con Rod & Main Bearing Set", "Material": "Tri-metal", "Size": "O/S 0.010\"" }, tags: ["main bearing", "crankshaft bearing", "0.010 oversize"] },
  { id: 32, name: "Main Bearing – O20", slug: "main-bearing-o20", description: "0.020\" oversize connecting rod and main crankshaft bearing set for Massey Ferguson tractors. For crankshafts reground to 0.020\" undersize.", shortDescription: "0.020\" oversize — All compatible MF", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 435, 590", rating: 4.5, reviewCount: 15, image: "/Tractor parts/Engine/Main Bearing & Metal/020/Main Bearing 020.jpeg", featured: false, inStock: true, specs: { "Type": "Con Rod & Main Bearing Set", "Material": "Tri-metal", "Size": "O/S 0.020\"" }, tags: ["main bearing", "crankshaft bearing", "0.020 oversize"] },
  { id: 33, name: "Main Bearing – O30", slug: "main-bearing-o30", description: "0.030\" oversize connecting rod and main crankshaft bearing set for Massey Ferguson tractors. For crankshafts reground to 0.030\" undersize.", shortDescription: "0.030\" oversize — All compatible MF", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 435, 590", rating: 4.5, reviewCount: 13, image: "/Tractor parts/Engine/Main Bearing & Metal/030/Main Bearing 030.jpg", featured: false, inStock: true, specs: { "Type": "Con Rod & Main Bearing Set", "Material": "Tri-metal", "Size": "O/S 0.030\"" }, tags: ["main bearing", "crankshaft bearing", "0.030 oversize"] },
  { id: 34, name: "Main Bearing – O40", slug: "main-bearing-o40", description: "0.040\" oversize connecting rod and main crankshaft bearing set for Massey Ferguson tractors. For crankshafts reground to 0.040\" undersize.", shortDescription: "0.040\" oversize — All compatible MF", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 435, 590", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Engine/Main Bearing & Metal/040/Main Bearing 040.jpg", featured: false, inStock: true, specs: { "Type": "Con Rod & Main Bearing Set", "Material": "Tri-metal", "Size": "O/S 0.040\"" }, tags: ["main bearing", "crankshaft bearing", "0.040 oversize"] },

  // ── TOP GASKETS ───────────────────────────────────────────────────────────

  { id: 40, name: "Top Gasket – 135", slug: "top-gasket-135", description: "Multi-layer steel cylinder head gasket for Massey Ferguson 135. Reliable high-compression seal resisting blow-out and coolant or oil leaks.", shortDescription: "Massey Ferguson 135", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135", rating: 5, reviewCount: 21, image: "/Tractor parts/Engine/Top Gasket/Head_Gasket_3638845Z1_Massey_Ferguson_Massey_Tractor_Parts_3638845Z1_2.webp", featured: false, inStock: true, specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel", "Series": "135" }, tags: ["top gasket", "head gasket", "massey ferguson 135"] },
  { id: 41, name: "Top Gasket – 265", slug: "top-gasket-265", description: "Multi-layer steel cylinder head gasket for Massey Ferguson 265. Reliable high-compression seal resisting blow-out and coolant or oil leaks.", shortDescription: "Massey Ferguson 265", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 5, reviewCount: 27, badge: "Top Rated", image: "/Tractor parts/Engine/Top Gasket/Head_Gasket_3638845Z1_Massey_Ferguson_Massey_Tractor_Parts_3638845Z1_2.webp", featured: true, inStock: true, specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel", "Series": "265" }, tags: ["top gasket", "head gasket", "massey ferguson 265"] },
  { id: 42, name: "Top Gasket – 290", slug: "top-gasket-290", description: "Multi-layer steel cylinder head gasket for Massey Ferguson 290. Reliable high-compression seal resisting blow-out and coolant or oil leaks.", shortDescription: "Massey Ferguson 290", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 290", rating: 5, reviewCount: 18, image: "/Tractor parts/Engine/Top Gasket/Head_Gasket_3638845Z1_Massey_Ferguson_Massey_Tractor_Parts_3638845Z1_2.webp", featured: false, inStock: true, specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel", "Series": "290" }, tags: ["top gasket", "head gasket", "massey ferguson 290"] },
  { id: 43, name: "Top Gasket – 375", slug: "top-gasket-375", description: "Multi-layer steel cylinder head gasket for Massey Ferguson 375. Reliable high-compression seal resisting blow-out and coolant or oil leaks.", shortDescription: "Massey Ferguson 375", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 5, reviewCount: 14, image: "/Tractor parts/Engine/Top Gasket/Head_Gasket_3638845Z1_Massey_Ferguson_Massey_Tractor_Parts_3638845Z1_2.webp", featured: false, inStock: true, specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel", "Series": "375" }, tags: ["top gasket", "head gasket", "massey ferguson 375"] },
  { id: 44, name: "Top Gasket – 435", slug: "top-gasket-435", description: "Multi-layer steel cylinder head gasket for Massey Ferguson 435. Reliable high-compression seal resisting blow-out and coolant or oil leaks.", shortDescription: "Massey Ferguson 435", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 435", rating: 5, reviewCount: 12, image: "/Tractor parts/Engine/Top Gasket/Head_Gasket_3638845Z1_Massey_Ferguson_Massey_Tractor_Parts_3638845Z1_2.webp", featured: false, inStock: true, specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel", "Series": "435" }, tags: ["top gasket", "head gasket", "massey ferguson 435"] },
  { id: 45, name: "Top Gasket – 590", slug: "top-gasket-590", description: "Multi-layer steel cylinder head gasket for Massey Ferguson 590. Reliable high-compression seal resisting blow-out and coolant or oil leaks.", shortDescription: "Massey Ferguson 590", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 590", rating: 5, reviewCount: 10, image: "/Tractor parts/Engine/Top Gasket/Head_Gasket_3638845Z1_Massey_Ferguson_Massey_Tractor_Parts_3638845Z1_2.webp", featured: false, inStock: true, specs: { "Type": "Cylinder Head Gasket", "Material": "Multi-Layer Steel", "Series": "590" }, tags: ["top gasket", "head gasket", "massey ferguson 590"] },

  // ── OTHER ENGINE PARTS ────────────────────────────────────────────────────

  { id: 50, name: "Air Filter", slug: "air-filter", description: "Heavy-duty multi-stage air filter for Massey Ferguson tractors. Removes dust, chaff and fine particles common in Nigerian farming environments, protecting the engine from abrasive wear.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 26, badge: "Best Seller", image: "/massey ferguson/Engine/air_filters.png", featured: true, inStock: true, specs: { "Type": "Dry Paper Element Air Filter", "Elements": "Primary + Safety" }, tags: ["air filter", "engine filter"] },
  { id: 51, name: "Fuel Filter", slug: "fuel-filter", description: "High-quality spin-on fuel filter with water separator for Massey Ferguson tractors. Removes water and particulates from diesel fuel to protect injection pump and injectors.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 28, badge: "Best Seller", image: "/massey ferguson/Engine/fuel_filters.png", featured: true, inStock: true, specs: { "Type": "Spin-on Fuel Filter with Water Separator", "Filtration": "5 micron" }, tags: ["fuel filter", "diesel filter", "water separator"] },
  { id: 52, name: "Water Pump", slug: "water-pump", description: "Engine water pump for Massey Ferguson tractors. Circulates coolant through the engine and radiator to maintain safe operating temperature. Centrifugal impeller design for high flow at low speeds.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 21, image: "/massey ferguson/Engine/water_pump.png", featured: false, inStock: true, specs: { "Type": "Centrifugal Water Pump", "Drive": "V-belt pulley", "Gasket Included": "Yes" }, tags: ["water pump", "coolant pump"] },
  { id: 53, name: "Fuel Injection Pump", slug: "fuel-injection-pump", description: "Remanufactured diesel fuel injection pump for Massey Ferguson tractors. Tested and calibrated to OEM delivery and timing specifications for maximum power and fuel economy.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 13, image: "/massey ferguson/Engine/fuel_injector_pump.png", featured: false, inStock: true, specs: { "Type": "CAV / Simms Inline Injection Pump (remanufactured)", "Governor": "Mechanical" }, tags: ["injection pump", "fuel injection pump"] },
  { id: 54, name: "Fuel Lift Pump", slug: "fuel-lift-pump", description: "Mechanical diaphragm fuel lift pump for Massey Ferguson tractors. Transfers diesel from the tank to the injection pump with consistent fuel delivery and manual priming lever.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 17, image: "/massey ferguson/Engine/fuel_pump.png", featured: false, inStock: true, specs: { "Type": "Mechanical Diaphragm Fuel Lift Pump", "Priming Lever": "Yes" }, tags: ["fuel lift pump", "fuel pump"] },
  { id: 55, name: "Oil Pump & Filter", slug: "oil-pump-filter", description: "Engine oil pump and filter kit for Massey Ferguson tractors. Gear-type pump maintains consistent oil pressure to all engine bearings, camshaft and valve gear even at low idle.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 20, image: "/massey ferguson/Engine/oil_pump_filter.png", featured: false, inStock: true, specs: { "Type": "Gear-type Oil Pump", "Filter Included": "Yes — full-flow spin-on" }, tags: ["oil pump", "oil filter"] },
  { id: 56, name: "Pistons & Rings Kit", slug: "pistons-rings-kit", description: "Complete matched piston and ring set for Massey Ferguson tractors. Includes aluminium-alloy pistons with gudgeon pins and a full set of compression and oil-control rings. Ready for engine overhaul.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 24, badge: "Best Seller", image: "/massey ferguson/Engine/pistons_rings.png", featured: true, inStock: true, specs: { "Contents": "Pistons, Gudgeon Pins, Circlips, Rings", "Piston Material": "Aluminium Alloy" }, tags: ["piston kit", "piston rings", "engine rebuild"] },
  { id: 57, name: "Turbocharger", slug: "turbocharger", description: "Remanufactured turbocharger for Massey Ferguson turbocharged models. Balanced to OEM specifications for smooth, reliable performance and increased power output.", shortDescription: "Turbocharged MF models", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 375T, 390T, 398, 4235, 4245, 4255", rating: 4.5, reviewCount: 10, image: "/massey ferguson/Engine/turbocharger.png", featured: false, inStock: true, specs: { "Type": "Remanufactured Turbocharger", "Max Boost": "1.0 bar" }, tags: ["turbocharger", "turbo"] },
  { id: 58, name: "Thermostat & Housing", slug: "thermostat-housing", description: "Engine thermostat and housing assembly for Massey Ferguson tractors. Maintains correct operating temperature with a wax-element thermostat that opens precisely at the specified temperature.", shortDescription: "All compatible MF series", category: "Engine Parts", categorySlug: "engine-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 13, image: "/massey ferguson/Engine/thermostat_housing.png", featured: false, inStock: true, specs: { "Contents": "Thermostat, Housing, Gasket", "Opening Temperature": "82°C" }, tags: ["thermostat", "cooling system"] },

  // ── HYDRAULICS ────────────────────────────────────────────────────────────

  { id: 70, name: "Hydraulic Pump", slug: "hydraulic-pump", description: "Complete hydraulic pump for Massey Ferguson tractors. Delivers consistent hydraulic pressure for lift systems, power steering and implement control. Direct replacement with no modification required.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 18, badge: "Top Rated", image: "/massey ferguson/Hydraulics/Hydraulic pump.webp", featured: true, inStock: true, specs: { "Type": "Gear-driven Hydraulic Pump", "Flow Rate": "32 L/min", "Operating Pressure": "200 bar" }, tags: ["hydraulic pump", "pump assembly"] },
  { id: 71, name: "Hydraulic Lift Pump", slug: "hydraulic-lift-pump", description: "OEM-compatible hydraulic lift pump for Massey Ferguson tractors. Powers the internal lift system for the 3-point hitch. Robust cast-iron body for long service life under sustained heavy lifting.", shortDescription: "3-point hitch — All compatible MF", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 5, reviewCount: 22, badge: "Best Seller", image: "/massey ferguson/Hydraulics/Lift Pump.jpg", featured: true, inStock: true, specs: { "Type": "Internal Gear Lift Pump", "Flow Rate": "28 L/min", "Body": "Cast Iron" }, tags: ["lift pump", "hydraulic lift pump", "3-point hitch"] },
  { id: 72, name: "Hydraulic Cylinder", slug: "hydraulic-cylinder", description: "Heavy-duty hydraulic cylinder for Massey Ferguson tractors. Used in the 3-point linkage lift system. Precision-honed bore for smooth, leak-free operation under high pressure.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 14, image: "/massey ferguson/Hydraulics/Hydraulic cylinder.webp", featured: false, inStock: true, specs: { "Type": "Double-acting Hydraulic Cylinder", "Bore": "63.5mm", "Stroke": "203mm" }, tags: ["hydraulic cylinder", "lift cylinder"] },
  { id: 73, name: "Hydraulic Hose", slug: "hydraulic-hose", description: "High-pressure wire-braided hydraulic hose for Massey Ferguson tractors. BSP ends for direct connection to tractor hydraulic circuits. Burst resistance up to 1000 bar.", shortDescription: "High-pressure BSP fitment", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson tractors — universal BSP fitment", rating: 4.5, reviewCount: 12, image: "/massey ferguson/Hydraulics/Hydraulic hose.webp", featured: false, inStock: true, specs: { "Type": "Wire-braided Hydraulic Hose", "Working Pressure": "250 bar", "Fittings": "BSP Standard" }, tags: ["hydraulic hose", "BSP hose"] },
  { id: 74, name: "Hydraulic Control Valve", slug: "hydraulic-control-valve", description: "Precision hydraulic control valve for Massey Ferguson tractors. Regulates oil flow to remote cylinders and implements with smooth spool action for precise positioning.", shortDescription: "Remote control — All compatible MF", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 10, image: "/massey ferguson/Hydraulics/Control valve.webp", featured: false, inStock: true, specs: { "Type": "Directional Control Valve", "Flow Rating": "40 L/min" }, tags: ["control valve", "remote valve"] },
  { id: 75, name: "Power Steering Pump", slug: "power-steering-pump", description: "Hydraulic power steering pump for Massey Ferguson tractors. Provides consistent oil pressure to the steering cylinder for effortless steering in heavy field conditions.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 16, image: "/massey ferguson/Hydraulics/power steering pump.jpg", featured: false, inStock: true, specs: { "Type": "Vane-type Power Steering Pump", "Flow Rate": "12 L/min" }, tags: ["power steering pump", "steering pump"] },

  // ── HYDRAULIC LINKAGE ─────────────────────────────────────────────────────

  { id: 76, name: "Upper Lift Arm", slug: "upper-lift-arm", description: "3-point linkage upper lift arm for Massey Ferguson tractors. Drop-forged steel with threaded adjustment for top link positioning. Connects the hydraulic lift ram to the upper link.", shortDescription: "MF 265, 375, 435", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Hydraulic-Linkage/Upper Arm/Upper Arm.webp", featured: false, inStock: true, specs: { "Type": "Upper Lift Arm", "Material": "Drop-forged Steel", "Hitch Category": "Cat I & II" }, tags: ["upper lift arm", "3-point linkage"] },
  { id: 77, name: "Lower Lift Arm (2-Hole)", slug: "lower-lift-arm-2-hole", description: "3-point linkage lower lift arm with 2-hole mounting pattern for Massey Ferguson 375. Heavy-duty forged steel withstands high draft and vertical implement loads. Cat II hitch ball end.", shortDescription: "2-hole — Massey Ferguson 375", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Hydraulic-Linkage/Lower Arm (2 Hole)/Lower Arm (2 Hole).webp", featured: false, inStock: true, specs: { "Type": "Lower Lift Arm (2-hole)", "Material": "Drop-forged Steel", "Ball End": "Cat II" }, tags: ["lower lift arm", "3-point linkage", "massey ferguson 375"] },
  { id: 78, name: "Ram Arm (Side Arm)", slug: "ram-arm-side-arm", description: "Hydraulic ram side arm for Massey Ferguson tractors. Connects the hydraulic ram to the lower lift arms, transmitting vertical force from the lift cylinder to the 3-point hitch.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Hydraulic-Linkage/Ram Arm (Side Arm)/Ram Arm (Side Arm).png", featured: false, inStock: true, specs: { "Type": "Hydraulic Ram Side Arm", "Material": "Drop-forged Steel" }, tags: ["ram arm", "side arm", "hydraulic linkage"] },
  { id: 79, name: "Ram Cover Assembly", slug: "ram-cover-assembly", description: "Hydraulic ram cover assembly for Massey Ferguson tractors. Seals and protects the hydraulic lift ram housing. Includes gasket and all retaining hardware.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 8, image: "/Tractor parts/Hydraulic-Linkage/Ram Cover Assembly/Ram Cover Assembly.jpg", featured: false, inStock: true, specs: { "Type": "Ram Cover Assembly", "Gasket Included": "Yes" }, tags: ["ram cover", "hydraulic ram"] },
  { id: 80, name: "Ram Lever", slug: "ram-lever", description: "Hydraulic ram control lever for Massey Ferguson tractors. Provides the mechanical link between the draft control mechanism and the hydraulic valve, regulating implement depth automatically.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 7, image: "/Tractor parts/Hydraulic-Linkage/Ram Lever/Ram Lever.webp", featured: false, inStock: true, specs: { "Type": "Ram Control Lever", "Material": "Forged Steel" }, tags: ["ram lever", "draft control"] },
  { id: 81, name: "Ram Plunger", slug: "ram-plunger", description: "Hydraulic ram plunger (piston rod) for Massey Ferguson tractors. Chrome-hardened and precision-ground rod provides linear actuating force in the hydraulic lift system.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Hydraulic-Linkage/Ram Plunger/Ram Plunger.webp", featured: false, inStock: true, specs: { "Type": "Ram Plunger / Piston Rod", "Material": "Chrome-hardened steel" }, tags: ["ram plunger", "hydraulic plunger", "piston rod"] },
  { id: 82, name: "Ram Shaft", slug: "ram-shaft", description: "Hydraulic ram shaft for Massey Ferguson tractors. Precision-machined and heat-treated for durability under cyclic loads of continuous field use.", shortDescription: "All compatible MF series", category: "Hydraulics", categorySlug: "hydraulics", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435", rating: 4.5, reviewCount: 8, image: "/Tractor parts/Hydraulic-Linkage/Ram Shaft/Ram Shaft.webp", featured: false, inStock: true, specs: { "Type": "Hydraulic Ram Shaft", "Material": "Heat-treated alloy steel" }, tags: ["ram shaft", "hydraulic shaft"] },

  // ── STEERING ──────────────────────────────────────────────────────────────

  { id: 90, name: "Steering Control Unit", slug: "steering-control-unit", description: "Hydrostatic steering control unit (orbitrol) for Massey Ferguson tractors. Converts steering wheel input into proportional hydraulic flow to the steering cylinder for smooth, load-independent response.", shortDescription: "MF 265, 375, 435, 590", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435, 590", rating: 4.5, reviewCount: 13, badge: "Top Rated", image: "/Tractor parts/Steering System/Steering Control Unit/Steering Control Unit.webp", featured: true, inStock: true, specs: { "Type": "Hydrostatic Steering Control Unit (Orbitrol)", "Displacement": "160 cc/rev" }, tags: ["steering control unit", "orbitrol"] },
  { id: 91, name: "Steering Box – MF 265", slug: "steering-box-mf265", description: "Reconditioned worm and sector steering gearbox for Massey Ferguson 265. Supplied pressure-tested and pre-set to factory backlash specification for precise, low-effort steering.", shortDescription: "Massey Ferguson 265", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Steering System/Steering Box/Steering Box – MF 265.jpg", featured: false, inStock: true, specs: { "Type": "Reconditioned Worm & Sector Steering Box", "Series": "265" }, tags: ["steering box", "massey ferguson 265"] },
  { id: 92, name: "Steering Cylinder – 265", slug: "steering-cylinder-265", description: "Double-acting hydraulic power steering cylinder for Massey Ferguson 265. Precision-honed bore for smooth, leak-free operation converting hydraulic pressure into steering force at the front axle.", shortDescription: "Massey Ferguson 265", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 14, image: "/Tractor parts/Steering System/Steering Cylinder/Steering Cylinder 265/Steering Cylinder  265.jpg", featured: false, inStock: true, specs: { "Type": "Double-acting Steering Cylinder", "Bore": "50mm", "Stroke": "180mm", "Series": "265" }, tags: ["steering cylinder", "massey ferguson 265"] },
  { id: 93, name: "Steering Cylinder – 375", slug: "steering-cylinder-375", description: "Double-acting hydraulic power steering cylinder for Massey Ferguson 375. Smooth, effortless steering in all field conditions.", shortDescription: "Massey Ferguson 375", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Steering System/Steering Cylinder/Steering Cylinder 375/Steering Cylinder 375.webp", featured: false, inStock: true, specs: { "Type": "Double-acting Steering Cylinder", "Bore": "50mm", "Series": "375" }, tags: ["steering cylinder", "massey ferguson 375"] },
  { id: 94, name: "Steering Cylinder – 435", slug: "steering-cylinder-435", description: "Double-acting hydraulic power steering cylinder for Massey Ferguson 435. Smooth, effortless steering in all field conditions.", shortDescription: "Massey Ferguson 435", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 435", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Steering System/Steering Cylinder/Steering Cylinder 435/Steering Cylinder 435.avif", featured: false, inStock: true, specs: { "Type": "Double-acting Steering Cylinder", "Bore": "50mm", "Series": "435" }, tags: ["steering cylinder", "massey ferguson 435"] },
  { id: 95, name: "Steering Cylinder – 595", slug: "steering-cylinder-595", description: "Double-acting hydraulic power steering cylinder for Massey Ferguson 595. Smooth, effortless steering in all field conditions.", shortDescription: "Massey Ferguson 595", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 595", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Steering System/Steering Cylinder/Steering Cylinder 595/Steering Cylinder 595.webp", featured: false, inStock: true, specs: { "Type": "Double-acting Steering Cylinder", "Bore": "50mm", "Series": "595" }, tags: ["steering cylinder", "massey ferguson 595"] },
  { id: 96, name: "Steering Pump Nut – 265", slug: "steering-pump-nut-265", description: "Retaining nut for the power steering pump drive on Massey Ferguson 265. Hardened steel with correct thread pitch for OEM torque specification.", shortDescription: "Massey Ferguson 265", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 8, image: "/Tractor parts/Steering System/Steering Pump Nut/Steering Pump Nut 265/Steering Pump Nut 265.jpeg", featured: false, inStock: true, specs: { "Type": "Steering Pump Drive Nut", "Material": "Hardened Steel", "Series": "265" }, tags: ["steering pump nut", "massey ferguson 265"] },
  { id: 97, name: "Steering Pump Nut – 375", slug: "steering-pump-nut-375", description: "Retaining nut for the power steering pump drive on Massey Ferguson 375. Hardened steel with correct thread pitch for OEM torque specification.", shortDescription: "Massey Ferguson 375", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 7, image: "/Tractor parts/Steering System/Steering Pump Nut/Steering Pump Nut 375/Steering Pump Nut 375.png", featured: false, inStock: true, specs: { "Type": "Steering Pump Drive Nut", "Material": "Hardened Steel", "Series": "375" }, tags: ["steering pump nut", "massey ferguson 375"] },
  { id: 98, name: "Steering Pump Pin – 265", slug: "steering-pump-pin-265", description: "Drive pin for the power steering pump on Massey Ferguson 265. Hardened steel locates the pump drive gear on the shaft and transmits torque under high hydraulic loads.", shortDescription: "Massey Ferguson 265", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Steering System/Steering Pump Pin/Steering Pump Pin 265/Steering Pump Pin 265.jpg", featured: false, inStock: true, specs: { "Type": "Steering Pump Drive Pin", "Material": "Hardened Steel", "Series": "265" }, tags: ["steering pump pin", "massey ferguson 265"] },
  { id: 99, name: "Ball Joint", slug: "ball-joint", description: "Heavy-duty front axle ball joint for Massey Ferguson tractors. Grease-nipple design allows regular lubrication. Precision-machined taper for secure, wobble-free fitment.", shortDescription: "All compatible MF series", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 16, image: "/massey ferguson/Steering and suspension/Ball joint.jpeg", featured: false, inStock: true, specs: { "Type": "Taper Shank Ball Joint", "Grease Nipple": "Yes" }, tags: ["ball joint", "front axle"] },
  { id: 100, name: "Tie Rods", slug: "tie-rods", description: "Adjustable front axle tie rods for Massey Ferguson tractors. Threaded-end adjustment for precise front wheel alignment. Forged steel construction for maximum strength under field loads.", shortDescription: "Adjustable — All compatible MF", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 14, image: "/massey ferguson/Steering and suspension/Tie rods.avif", featured: false, inStock: true, specs: { "Type": "Adjustable Tie Rod (pair)", "Material": "Forged Steel" }, tags: ["tie rod", "wheel alignment"] },
  { id: 101, name: "Steering Arms", slug: "steering-arms", description: "Heavy-duty front axle steering arms for Massey Ferguson tractors. Drop-forged steel withstands high lateral farm loads. Matched pair supplied for complete axle replacement.", shortDescription: "Pair — All compatible MF", category: "Steering & Suspension", categorySlug: "steering-suspension", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 11, image: "/massey ferguson/Steering and suspension/steering-arms.webp", featured: false, inStock: true, specs: { "Type": "Drop-forged Steering Arm (pair)", "Material": "High-tensile forged steel" }, tags: ["steering arm", "front axle"] },

  // ── BRAKES ────────────────────────────────────────────────────────────────

  { id: 110, name: "Brake Pad Set", slug: "brake-pad-set", description: "Heavy-duty semi-metallic brake pad set for Massey Ferguson tractors. Strong braking performance in wet and muddy conditions. Includes hardware clips and shims for complete installation.", shortDescription: "Disc brake — MF 375, 390, 435, 590", category: "Brakes", categorySlug: "brakes", brand: "OEM Compatible", compatibility: "Massey Ferguson 375, 390, 435, 590 (disc brake models)", rating: 4.5, reviewCount: 18, badge: "Best Seller", image: "/massey ferguson/Brakes/brake pad.jpeg", featured: true, inStock: true, specs: { "Material": "Semi-metallic", "Thickness": "12mm", "Hardware Included": "Yes" }, tags: ["brake pad", "disc brake"] },

  { id: 111, name: "Brake Shoe Set", slug: "brake-shoe-set", description: "Complete pre-lined brake shoe set for Massey Ferguson drum brake tractors. Non-asbestos organic lining. Sold as a complete axle set (4 shoes).", shortDescription: "Drum brake — All compatible MF", category: "Brakes", categorySlug: "brakes", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390", rating: 4.5, reviewCount: 14, image: "/massey ferguson/Brakes/brake shoe.jpg", featured: false, inStock: true, specs: { "Type": "Pre-lined Brake Shoe Set", "Lining": "Non-asbestos Organic", "Quantity": "4 shoes" }, tags: ["brake shoe", "drum brake"] },

  { id: 112, name: "Brake Drum", slug: "brake-drum", description: "Precision-turned cast iron brake drum for Massey Ferguson tractors. Consistent braking performance for both field and road use.", shortDescription: "All compatible MF series", category: "Brakes", categorySlug: "brakes", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 11, image: "/massey ferguson/Brakes/Brake drum.jpeg", featured: false, inStock: true, specs: { "Material": "Cast Iron", "Drum Diameter": "280mm" }, tags: ["brake drum", "drum brake"] },

  { id: 113, name: "Brake Cylinder", slug: "brake-cylinder", description: "Hydraulic brake wheel cylinder for Massey Ferguson tractors. Converts hydraulic pressure into mechanical force at the brake shoes. Supplied with rubber boots and seals for a complete rebuild.", shortDescription: "All compatible MF series", category: "Brakes", categorySlug: "brakes", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 13, image: "/massey ferguson/Brakes/Brake cylinder.webp", featured: false, inStock: true, specs: { "Type": "Hydraulic Wheel Cylinder", "Bore": "25.4mm", "Boots Included": "Yes" }, tags: ["brake cylinder", "wheel cylinder"] },

  { id: 114, name: "Brake Lining", slug: "brake-lining", description: "Non-asbestos organic brake lining for Massey Ferguson tractors. Consistent friction coefficient with fade resistance under sustained braking. Sold per set (4 pieces).", shortDescription: "Non-asbestos — All compatible MF", category: "Brakes", categorySlug: "brakes", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 15, image: "/massey ferguson/Brakes/brake lining.jpg", featured: false, inStock: true, specs: { "Material": "Non-asbestos Organic (NAO)", "Thickness": "8mm", "Quantity": "4 pieces" }, tags: ["brake lining", "brake friction"] },

  // ── TRANSMISSION ──────────────────────────────────────────────────────────

  { id: 120, name: "Clutch Kit", slug: "clutch-kit", description: "Complete clutch kit for Massey Ferguson tractors. Includes pressure plate assembly, clutch disc and release bearing. Organic friction facing for smooth engagement and long service life.", shortDescription: "Complete kit — All compatible MF", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 27, badge: "Best Seller", image: "/massey ferguson/Transmission/clutch_assembly/mf_clutch_kit.jpg", featured: true, inStock: true, specs: { "Contents": "Pressure Plate, Clutch Disc, Release Bearing", "Disc Diameter": "280mm" }, tags: ["clutch kit", "clutch disc", "pressure plate"] },

  { id: 121, name: "3rd Gear Shaft – 21/6", slug: "3rd-gear-shaft-21-6", description: "3rd gear layshaft (21/6 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision ground. Direct OEM replacement for MF 265, 375, 435.", shortDescription: "21/6 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 8, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear shaft/21-6/21-6.webp", featured: false, inStock: true, specs: { "Type": "3rd Gear Layshaft", "Teeth": "21 / 6", "Material": "Case-hardened Alloy Steel" }, tags: ["3rd gear shaft", "layshaft"] },

  { id: 122, name: "3rd Gear Shaft – 24/10", slug: "3rd-gear-shaft-24-10", description: "3rd gear layshaft (24/10 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision ground. Direct OEM replacement for MF 265, 375, 435.", shortDescription: "24/10 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear shaft/24-10/24-10.webp", featured: false, inStock: true, specs: { "Type": "3rd Gear Layshaft", "Teeth": "24 / 10", "Material": "Case-hardened Alloy Steel" }, tags: ["3rd gear shaft", "layshaft"] },

  { id: 123, name: "3rd Gear Shaft – 24/21", slug: "3rd-gear-shaft-24-21", description: "3rd gear layshaft (24/21 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision ground. Direct OEM replacement for MF 265, 375, 435.", shortDescription: "24/21 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear shaft/24-21/24-21.jpg", featured: false, inStock: true, specs: { "Type": "3rd Gear Layshaft", "Teeth": "24 / 21", "Material": "Case-hardened Alloy Steel" }, tags: ["3rd gear shaft", "layshaft"] },

  { id: 124, name: "3rd Gear Shaft – 26/10", slug: "3rd-gear-shaft-26-10", description: "3rd gear layshaft (26/10 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision ground. Direct OEM replacement for MF 265, 375, 435.", shortDescription: "26/10 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear shaft/26-10/26-10.jpg", featured: false, inStock: true, specs: { "Type": "3rd Gear Layshaft", "Teeth": "26 / 10", "Material": "Case-hardened Alloy Steel" }, tags: ["3rd gear shaft", "layshaft"] },

  { id: 125, name: "3rd Gear Shaft – 26/21", slug: "3rd-gear-shaft-26-21", description: "3rd gear layshaft (26/21 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision ground. Direct OEM replacement for MF 265, 375, 435.", shortDescription: "26/21 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear shaft/26-21/26-21.jpg", featured: false, inStock: true, specs: { "Type": "3rd Gear Layshaft", "Teeth": "26 / 21", "Material": "Case-hardened Alloy Steel" }, tags: ["3rd gear shaft", "layshaft"] },

  { id: 126, name: "3rd Gear Tube – 265", slug: "3rd-gear-tube-265", description: "Layshaft gear spacer tube for the 3rd gear assembly on Massey Ferguson 265. Positions the needle roller bearing on the layshaft and maintains correct gear spacing.", shortDescription: "Massey Ferguson 265", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear Tube/265/3rd Gear Tube – 265.jpeg", featured: false, inStock: true, specs: { "Type": "Layshaft Gear Spacer Tube", "Series": "265" }, tags: ["3rd gear tube", "layshaft tube"] },

  { id: 127, name: "3rd Gear Tube – 375", slug: "3rd-gear-tube-375", description: "Layshaft gear spacer tube for the 3rd gear assembly on Massey Ferguson 375. Positions the needle roller bearing on the layshaft and maintains correct gear spacing.", shortDescription: "Massey Ferguson 375", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 8, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/3rd Gear Tube/375/3rd Gear Tube 375.jpeg", featured: false, inStock: true, specs: { "Type": "Layshaft Gear Spacer Tube", "Series": "375" }, tags: ["3rd gear tube", "layshaft tube"] },

  { id: 128, name: "3rd Gear Bearing", slug: "3rd-gear-bearing", description: "Needle roller bearing for the Massey Ferguson 3rd gear layshaft. Supports the gear cluster on the layshaft tube and absorbs radial loads during power transmission.", shortDescription: "MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 13, image: "/Tractor parts/Transmission or Gearbox/Gear Accessories/3rd Gear Bearing/Gear Bearing.webp", featured: false, inStock: true, specs: { "Type": "Needle Roller Bearing", "Application": "3rd Gear Layshaft" }, tags: ["3rd gear bearing", "needle bearing"] },

  { id: 129, name: "3rd Gear Washer – 265", slug: "3rd-gear-washer-265", description: "Thrust washer for the 3rd gear layshaft on Massey Ferguson 265. Hardened steel controls end-float on the gear cluster and prevents metal-to-metal contact.", shortDescription: "Massey Ferguson 265", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Transmission or Gearbox/Gear Accessories/3rd Gear Washer/3rd Gear Washer 265/Gear washer 265.webp", featured: false, inStock: true, specs: { "Type": "Thrust Washer", "Material": "Hardened Steel", "Series": "265" }, tags: ["3rd gear washer", "thrust washer"] },

  { id: 130, name: "3rd Gear Washer – 375", slug: "3rd-gear-washer-375", description: "Thrust washer for the 3rd gear layshaft on Massey Ferguson 375. Hardened steel controls end-float on the gear cluster and prevents metal-to-metal contact.", shortDescription: "Massey Ferguson 375", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Transmission or Gearbox/Gear Accessories/3rd Gear Washer/3rd Gear Washer 375/3rd Gear Washer 375.jpg", featured: false, inStock: true, specs: { "Type": "Thrust Washer", "Material": "Hardened Steel", "Series": "375" }, tags: ["3rd gear washer", "thrust washer"] },

  { id: 131, name: "3rd Gear Washer – 435", slug: "3rd-gear-washer-435", description: "Thrust washer for the 3rd gear layshaft on Massey Ferguson 435. Hardened steel controls end-float and prevents gear-on-gear contact.", shortDescription: "Massey Ferguson 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 435", rating: 4.5, reviewCount: 8, image: "/Tractor parts/Transmission or Gearbox/Gear Accessories/3rd Gear Washer/3rd Gear Washer 435/Gear washer 435.webp", featured: false, inStock: true, specs: { "Type": "Thrust Washer", "Material": "Hardened Steel", "Series": "435" }, tags: ["3rd gear washer", "thrust washer"] },

  { id: 132, name: "Gear 42/20", slug: "gear-42-20", description: "Constant mesh gear (42/20 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision hobbed and ground for quiet, efficient power transmission.", shortDescription: "42/20 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Transmission or Gearbox/Gears/Gear 42-20/42-20.webp", featured: false, inStock: true, specs: { "Type": "Constant Mesh Gear", "Teeth": "42 / 20" }, tags: ["gear 42/20", "constant mesh gear"] },

  { id: 133, name: "Gear 33/18", slug: "gear-33-18", description: "Constant mesh gear (33/18 tooth) for Massey Ferguson gearboxes. Case-hardened alloy steel, precision hobbed and ground for quiet, efficient power transmission.", shortDescription: "33/18 tooth — MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Transmission or Gearbox/Gears/Gear 33-18/Gear 33-18.webp", featured: false, inStock: true, specs: { "Type": "Constant Mesh Gear", "Teeth": "33 / 18" }, tags: ["gear 33/18", "constant mesh gear"] },

  { id: 134, name: "3rd Gear", slug: "3rd-gear", description: "Replacement 3rd speed gear for Massey Ferguson gearboxes. Case-hardened alloy steel with precision-ground teeth for quiet, reliable power transmission.", shortDescription: "MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 13, image: "/Tractor parts/Transmission or Gearbox/Gears/Gear 3/Gear 3.jpg", featured: false, inStock: true, specs: { "Type": "3rd Speed Gear", "Material": "Case-hardened Alloy Steel" }, tags: ["3rd gear", "speed gear"] },

  { id: 135, name: "4th Gear", slug: "4th-gear", description: "Replacement 4th speed gear for Massey Ferguson gearboxes. Case-hardened alloy steel, precision ground for smooth engagement in the top direct-drive range.", shortDescription: "MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Transmission or Gearbox/Gears/Gear 4/4th-gear.jpg", featured: false, inStock: true, specs: { "Type": "4th Speed Gear", "Material": "Case-hardened Alloy Steel" }, tags: ["4th gear", "speed gear"] },

  { id: 136, name: "Reverse Gear", slug: "reverse-gear", description: "Replacement reverse idler gear for Massey Ferguson gearboxes. Case-hardened alloy steel for reliable reverse engagement. Direct OEM replacement.", shortDescription: "MF 265, 375, 435", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 14, image: "/Tractor parts/Transmission or Gearbox/Gears/Reverse Gear/Reverse Gear.jpg", featured: false, inStock: true, specs: { "Type": "Reverse Idler Gear", "Material": "Case-hardened Alloy Steel" }, tags: ["reverse gear", "idler gear"] },

  { id: 137, name: "Main Shaft – 265", slug: "main-shaft-265", description: "Gearbox main (output) shaft for Massey Ferguson 265. Heat-treated alloy steel for torsional strength. Carries all forward and reverse gears through to the rear axle.", shortDescription: "Massey Ferguson 265", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 265", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/Main Shaft/265/265.jpg", featured: false, inStock: true, specs: { "Type": "Gearbox Main Shaft", "Material": "Heat-treated Alloy Steel", "Series": "265" }, tags: ["main shaft", "gearbox shaft"] },

  { id: 138, name: "Main Shaft – 375", slug: "main-shaft-375", description: "Gearbox main (output) shaft for Massey Ferguson 375. Heat-treated alloy steel for torsional strength. Direct OEM replacement.", shortDescription: "Massey Ferguson 375", category: "Transmission", categorySlug: "transmission", brand: "OEM Compatible", compatibility: "Massey Ferguson 375", rating: 4.5, reviewCount: 9, image: "/Tractor parts/Transmission or Gearbox/Gear Shafts & Internal Parts/Main Shaft/375/375.jpeg", featured: false, inStock: true, specs: { "Type": "Gearbox Main Shaft", "Material": "Heat-treated Alloy Steel", "Series": "375" }, tags: ["main shaft", "gearbox shaft"] },

  // ── TRACTOR PARTS (FRONT AXLE, HITCH, SEAT) ─────────────────────────────

  { id: 140, name: "Front Wheel Hub", slug: "front-wheel-hub", description: "Precision-machined cast iron front wheel hub for Massey Ferguson tractors. Correct bolt-circle for front rim fitment. Includes wheel studs and ready for taper roller bearing fitment.", shortDescription: "MF 165, 265, 375, 435", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 165, 265, 375, 435", rating: 4.5, reviewCount: 14, image: "/Tractor parts/Front Axle & Wheel/Front Wheel Hub/Front Wheel Hub.jpg", featured: false, inStock: true, specs: { "Type": "Front Wheel Hub", "Material": "Cast Iron", "Wheel Studs": "Included" }, tags: ["front wheel hub", "front hub"] },

  { id: 141, name: "Front Wheel Rim", slug: "front-wheel-rim", description: "Steel front wheel rim for Massey Ferguson tractors. Correct offset and bolt-circle for OEM front axle hub fitment. Compatible with standard front tractor tire sizes.", shortDescription: "MF 265, 375, 435", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Front Axle & Wheel/Front Wheel Rim/Front Wheel Rim.webp", featured: false, inStock: true, specs: { "Type": "Front Wheel Rim", "Material": "Steel", "Rim Width": "4.5\"" }, tags: ["front wheel rim", "front rim"] },

  { id: 142, name: "Front Wheel Bolt", slug: "front-wheel-bolt", description: "High-tensile front wheel retaining stud and nut set for Massey Ferguson tractors. Secure rim fitment. Sold per wheel set.", shortDescription: "MF 165, 265, 375", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 165, 265, 375", rating: 4.5, reviewCount: 16, image: "/Tractor parts/Front Axle & Wheel/Front Wheel Bolt/Front Wheel Bolt.webp", featured: false, inStock: true, specs: { "Type": "Front Wheel Stud & Nut Set", "Material": "High-tensile Steel", "Grade": "8.8" }, tags: ["wheel bolt", "front wheel bolt"] },

  { id: 143, name: "Front Spindle", slug: "front-spindle", description: "Drop-forged front axle spindle (stub axle) for Massey Ferguson tractors. Carries the front wheel hub bearing load. Precision-machined journals for correct bearing seating and long service life.", shortDescription: "MF 265, 375, 435, 590", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 265, 375, 435, 590", rating: 4.5, reviewCount: 13, image: "/Tractor parts/Front Axle & Wheel/Front Spindle/Front Spindle.webp", featured: false, inStock: true, specs: { "Type": "Front Axle Stub Spindle", "Material": "Drop-forged Steel" }, tags: ["front spindle", "stub axle", "kingpin"] },

  { id: 144, name: "Top Link", slug: "top-link", description: "Adjustable top link for Massey Ferguson 3-point hitch. Telescopic adjustment allows fine-tuning of implement pitch angle for different implements and soil conditions.", shortDescription: "3-point hitch — All compatible MF", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 14, image: "/Tractor parts/Linkage & Hitch Parts/Top Link/Top Link.jpeg", featured: false, inStock: true, specs: { "Type": "Adjustable Top Link", "Material": "Forged Steel", "Hitch Category": "Cat I & II" }, tags: ["top link", "3-point hitch", "linkage"] },

  { id: 145, name: "Lower Link (Side Link)", slug: "lower-link-side-link", description: "Check chain and side link assembly for Massey Ferguson 3-point hitch. Controls lateral sway of mounted implements. Adjustable length for correct tracking behind the tractor.", shortDescription: "3-point hitch — All compatible MF", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 11, image: "/Tractor parts/Linkage & Hitch Parts/Lower Link (Side Link)/Lower Link (Side Link).jpeg", featured: false, inStock: true, specs: { "Type": "Lower Link / Check Chain", "Adjustment": "Turnbuckle", "Hitch Category": "Cat I & II" }, tags: ["lower link", "side link", "check chain"] },

  { id: 146, name: "Leveling Fork and Box", slug: "leveling-fork-box", description: "Leveling box and fork assembly for Massey Ferguson 3-point linkage. Independent adjustment of each lower link height for leveling implements on side slopes.", shortDescription: "3-point hitch — All compatible MF", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Linkage & Hitch Parts/Leveling Fork and Box/Leveling Fork and Box.webp", featured: false, inStock: true, specs: { "Type": "Leveling Box & Fork Assembly", "Material": "Cast Iron / Forged Steel" }, tags: ["leveling box", "leveling fork", "3-point hitch"] },

  { id: 147, name: "Tractor Seat", slug: "tractor-seat", description: "Replacement operator seat for Massey Ferguson tractors. High-density foam cushion for comfort on long working days. Adjustable fore/aft slide. UV-resistant vinyl covering.", shortDescription: "All compatible MF series", category: "Tractor Parts", categorySlug: "tractor-parts", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 15, image: "/Tractor parts/Tractor Body Parts/Tractor Seat/Tractor Seat.webp", featured: false, inStock: true, specs: { "Type": "Operator Seat", "Cushion": "High-density foam", "Covering": "UV-resistant vinyl", "Adjustment": "Fore/aft slide" }, tags: ["tractor seat", "operator seat"] },

  // ── ELECTRICAL ────────────────────────────────────────────────────────────

  { id: 150, name: "Starter Motor", slug: "starter-motor", description: "Heavy-duty pre-engaged starter motor for Massey Ferguson tractors. High-torque design handles the compression demands of direct-injection diesel engines for reliable cold and hot starting.", shortDescription: "All compatible MF series", category: "Electrical", categorySlug: "electrical", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 22, badge: "Best Seller", image: "/massey ferguson/Electrical/starter_motor/starter_motor_tractor.jpg", featured: true, inStock: true, specs: { "Type": "Pre-engaged Starter Motor", "Voltage": "12V", "Power": "2.8 kW" }, tags: ["starter motor", "tractor starter"] },

  { id: 151, name: "Alternator", slug: "alternator", description: "Heavy-duty 14V alternator for Massey Ferguson tractors. Reliable charging for all electrical systems including lighting and instruments. Direct bolt-on replacement requiring no wiring modifications.", shortDescription: "14V — Modern MF series", category: "Electrical", categorySlug: "electrical", brand: "OEM Compatible", compatibility: "Massey Ferguson 375, 390, 435, 4235, 4245, 4255, 4265", rating: 4.5, reviewCount: 19, image: "/massey ferguson/Electrical/alternator_generator/alternator_modern.jpg", featured: false, inStock: true, specs: { "Voltage": "14V", "Amperage": "65A", "Regulator": "Internal" }, tags: ["alternator", "charging system"] },

  { id: 152, name: "Dynamo / Generator – MF 135", slug: "dynamo-mf135", description: "Original-type DC dynamo for classic Massey Ferguson 135 and early-series tractors. Rebuilt to OEM output specification for correct charging on 12V negative-earth systems.", shortDescription: "MF 135 & early models", category: "Electrical", categorySlug: "electrical", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 148, 165 (early series)", rating: 4.5, reviewCount: 14, image: "/massey ferguson/Electrical/older_models/mf135_dynamo.jpg", featured: false, inStock: true, specs: { "Type": "DC Dynamo (Generator)", "Voltage": "12V", "Drive": "Belt-driven" }, tags: ["dynamo", "generator", "massey ferguson 135"] },

  { id: 153, name: "Wiring Harness", slug: "wiring-harness", description: "Complete replacement wiring harness for Massey Ferguson tractors. All circuits pre-terminated with OEM-matched connectors. UV-stabilised insulation for outdoor field use.", shortDescription: "All compatible MF series", category: "Electrical", categorySlug: "electrical", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 10, image: "/massey ferguson/Electrical/cables_wiring/wiring_harness.jpg", featured: false, inStock: true, specs: { "Type": "Complete Wiring Harness", "Insulation": "UV-stabilised PVC" }, tags: ["wiring harness", "electrical loom"] },

  { id: 154, name: "Ignition Switch & Keys", slug: "ignition-switch-keys", description: "Replacement ignition switch with two keys for Massey Ferguson tractors. Start, run and accessory positions. Direct plug-in connector for fast installation.", shortDescription: "All compatible MF series", category: "Electrical", categorySlug: "electrical", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 16, image: "/massey ferguson/Electrical/ignition_switch/ignition_switch_keys.jpg", featured: false, inStock: true, specs: { "Type": "Ignition Switch", "Positions": "Off / Accessory / Run / Start", "Keys": "2" }, tags: ["ignition switch", "key switch"] },

  { id: 155, name: "Tractor Lights Set", slug: "tractor-lights-set", description: "Complete lighting kit for Massey Ferguson tractors. Includes front headlights and rear work lights. Sealed beam lenses resist dust, moisture and vibration. Plug-and-play with OEM wiring harness.", shortDescription: "All compatible MF series", category: "Electrical", categorySlug: "electrical", brand: "OEM Compatible", compatibility: "Massey Ferguson 135, 165, 265, 290, 375, 390, 435, 590", rating: 4.5, reviewCount: 13, image: "/massey ferguson/Electrical/lights/tractor_lights_set.jpg", featured: false, inStock: true, specs: { "Contents": "2× Front Headlights, 2× Rear Work Lights", "Voltage": "12V" }, tags: ["tractor lights", "headlights", "work lights"] },

  // ── FARM IMPLEMENTS ───────────────────────────────────────────────────────

  { id: 160, name: "Complete Plough", slug: "complete-plough", description: "Heavy-duty 3-disc plough for primary tillage in Nigerian soil conditions including heavy clay soils of the south and sandy loam of the north. Adjustable disc angle and working depth. Universal Cat I & II 3-point hitch.", shortDescription: "3-disc — Cat I & II 3-point hitch", category: "Farm Implements", categorySlug: "farm-implements", brand: "OEM Compatible", compatibility: "Universal 3-point hitch, Cat I & II", rating: 4.5, reviewCount: 22, badge: "Best Seller", image: "/Tractor parts/Farm Implements/Plough/Complete Plough/Complete Plough.avif", featured: true, inStock: true, specs: { "Type": "Disc Plough", "Discs": "3", "Disc Diameter": "610mm", "Working Depth": "200–350mm", "Hitch": "Cat I & II" }, tags: ["plough", "disc plough", "tillage"] },

  { id: 161, name: "Plough Disc", slug: "plough-disc", description: "Replacement boron steel disc blade for agricultural disc ploughs. Heat-treated for maximum hardness and wear resistance in Nigerian soils. Fits standard plough frames.", shortDescription: "Replacement blade — 610mm", category: "Farm Implements", categorySlug: "farm-implements", brand: "OEM Compatible", compatibility: "Standard disc ploughs — universal fitment", rating: 4.5, reviewCount: 18, image: "/Tractor parts/Farm Implements/Plough/Plough Disc/Plough Disc.avif", featured: false, inStock: true, specs: { "Material": "Boron Steel", "Diameter": "610mm (24\")", "Thickness": "6mm" }, tags: ["plough disc", "disc blade", "tillage"] },

  { id: 162, name: "Plough Frame", slug: "plough-frame", description: "Heavy-duty main frame assembly for disc ploughs. High-tensile steel welded to OEM tolerances. All hitch mounting points and disc gang bearings pre-machined. Supplied primed.", shortDescription: "3-disc plough frame — Universal hitch", category: "Farm Implements", categorySlug: "farm-implements", brand: "OEM Compatible", compatibility: "Standard 3-disc plough frames", rating: 4.5, reviewCount: 10, image: "/Tractor parts/Farm Implements/Plough/Plough Frame/Plough Frame.avif", featured: false, inStock: true, specs: { "Material": "High-tensile Steel", "Hitch": "Cat I & II", "Disc Positions": "3" }, tags: ["plough frame", "disc plough frame"] },

  { id: 163, name: "Plough Hub", slug: "plough-hub", description: "Disc plough hub assembly with sealed taper roller bearings. Grease-nipple design for regular lubrication and extended bearing life in abrasive soil conditions.", shortDescription: "Disc plough — Universal fitment", category: "Farm Implements", categorySlug: "farm-implements", brand: "OEM Compatible", compatibility: "Standard disc ploughs", rating: 4.5, reviewCount: 12, image: "/Tractor parts/Farm Implements/Plough/Plough Hub/Plough Hub.jpeg", featured: false, inStock: true, specs: { "Type": "Disc Hub Assembly", "Bearings": "Sealed taper roller", "Grease Nipple": "Yes" }, tags: ["plough hub", "disc hub", "plough bearing"] },

  { id: 164, name: "Complete Ridger", slug: "complete-ridger", description: "Complete disc ridger for forming planting ridges and earthing up crops. Widely used across Nigerian yam, cassava and maize farms. Adjustable disc angle and working depth. Universal 3-point hitch.", shortDescription: "2-disc — Cat I & II 3-point hitch", category: "Farm Implements", categorySlug: "farm-implements", brand: "OEM Compatible", compatibility: "Universal 3-point hitch, Cat I & II", rating: 4.5, reviewCount: 19, badge: "Best Seller", image: "/Tractor parts/Farm Implements/Ridger/Complete Ridger/Complete Ridger.jpg", featured: true, inStock: true, specs: { "Type": "Disc Ridger", "Discs": "2", "Working Width": "600–900mm adjustable", "Hitch": "Cat I & II" }, tags: ["ridger", "disc ridger", "yam ridger", "ridging"] },

  { id: 165, name: "Ridger Disc", slug: "ridger-disc", description: "Replacement boron steel disc blade for agricultural ridgers. Heat-treated for excellent hardness and wear life in Nigerian soils. Suitable for all standard ridger frames.", shortDescription: "Replacement blade — 510mm", category: "Farm Implements", categorySlug: "farm-implements", brand: "OEM Compatible", compatibility: "Standard disc ridgers — universal fitment", rating: 4.5, reviewCount: 15, image: "/Tractor parts/Farm Implements/Ridger/Ridger Disc/Ridger Disc.avif", featured: false, inStock: true, specs: { "Material": "Boron Steel", "Diameter": "510mm (20\")", "Thickness": "5mm" }, tags: ["ridger disc", "ridger blade", "ridging"] },

];


export const reviews: Review[] = [
  { id: 1, author: "Oluwaseun Adebayo", role: "Farm Owner", location: "Ogun State", rating: 5, content: "Found the exact hydraulic pump I needed for my Massey Ferguson when no one else could help. Delivered to Abeokuta in just 2 days!", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80" },
  { id: 2, author: "Chinedu Okonkwo", role: "Mechanic", location: "Lagos", rating: 4, content: "Their prices are very competitive compared to other suppliers in Lagos. I've saved over ₦200,000 on parts this year alone.", avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b1a8?w=100&q=80" },
  { id: 3, author: "Emeka Nwosu", role: "Agricultural Engineer", location: "Anambra State", rating: 5, content: "The quality of parts from Unique Truth is consistently excellent. I always recommend them to farmers who need reliable tractor components.", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80" },
  { id: 4, author: "Fatima Aliyu", role: "Farm Manager", location: "Kano State", rating: 5, content: "Fast delivery nationwide is not a joke here. My engine parts arrived in Kano within 4 days. Exceptional service!", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80" },
];

// ─── SITE CONFIG ──────────────────────────────────────────────────────────────

const phone = process.env.NEXT_PUBLIC_PHONE || "—";
const whatsapp = process.env.NEXT_PUBLIC_WHATSAPP || "";
const email = process.env.NEXT_PUBLIC_EMAIL || "";
const address = process.env.NEXT_PUBLIC_ADDRESS || "";
const hours = process.env.NEXT_PUBLIC_HOURS || "Mon-Sat: 8am – 6pm";
const fbUrl = process.env.NEXT_PUBLIC_FACEBOOK_URL || "";
const twitterUrl = process.env.NEXT_PUBLIC_TWITTER_URL || "";
const igUrl = process.env.NEXT_PUBLIC_INSTAGRAM_URL || "";
const founded = "2018";

export const siteImages = {
  logo: "/logo.avif",
  favicon: process.env.NEXT_PUBLIC_FAVICON_URL || "",
  hero: process.env.NEXT_PUBLIC_HERO_IMAGE_URL || "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1600&q=80",
  about: process.env.NEXT_PUBLIC_ABOUT_IMAGE_URL || "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
};

export const siteConfig = {
  name: "Unique Truth Auto Limited",
  tagline: "Your Trusted Source for Tractors & Parts in Nigeria",
  description: "Nigeria's leading independent distributor of agricultural tractors and spare parts. Premium quality parts for Massey Ferguson, Fiat, Ford, Mahindra, New Holland, Sonalika, Steyr, Swaraj and more.",
  address, phone, whatsapp, email, hours, founded,
  yearsExperience: new Date().getFullYear() - parseInt(founded),
  stats: { partsInStock: "5,000+", satisfiedCustomers: "1,000+", statesCovered: "36" },
  socialMedia: { facebook: fbUrl, twitter: twitterUrl, instagram: igUrl, whatsapp: whatsapp ? `https://wa.me/${whatsapp.replace("+", "")}` : "" },
  keywords: ["tractor parts Nigeria", "agricultural machinery Lagos", "Massey Ferguson parts Nigeria", "Ford tractor Nigeria", "Fiat tractor Nigeria", "Mahindra tractor Nigeria", "New Holland Nigeria", "tractor spare parts Nigeria", "buy tractor online Nigeria"],
};